chainguard-dev/apko

.ko.yaml, config/task.yaml
To build/install the task definition (w/ apko) you can run:
```
KO_DOCKER_REPO=ghcr.io/mattmoor ko apply -Bf config/
```
This task definition implements the interface defined in `github.com/mattmoor/mink`
to support uploading local source and directing where to publish images (so it can
be used with `mink apply` as well).
You can invoke this task imperatively with the following `mink` command:
```
$ mink run task apko --as=apko -- --path=./examples/nginx.yaml
2022/02/19 19:21:58 building image 'gcr.io/mattmoor-chainguard/images' from config file './examples/nginx.yaml'
2022/02/19 19:21:58 build context:
2022/02/19 19:21:58   image configuration: {{[https://dl-cdn.alpinelinux.org/alpine/edge/main] [/etc/apk/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub …
```
=> Add task to support running `apko` builds via Tekton.

cmd/apko/cli/build.go, cmd/apko/cli/commands.go, cmd/apko/cli/publish.go, go.mod, go.sum, pkg/build/oci/oci.go
Introduces `apko` publishing, use `docker login` or equivalent to set up the docker keychain first.
Example published image on Docker Hub (haha I couldn't help myself): https://hub.docker.com/repository/docker/kaniini/apko-example
=> feature: apko publishing

.github/workflows/release.yaml, .goreleaser.yaml
Here's a sample release on my fork: https://github.com/mattmoor/apko/releases/tag/v0.0.11
I downloaded and verified the signature here (still not sure what the ctlog issue is cc @dlorenc ):
```
$ COSIGN_EXPERIMENTAL=true cosign verify-blob --signature apko_0.0.11_linux_arm64.sig --cert apko_0.0.11_linux_arm64.crt apko_0.0.11_linux_arm64/apko 
Verified OK
Error: verifying blob [apko_0.0.11_linux_arm64/apko]: signature not found in transparency log
main.go:46: error during command execution: verifying blob [apko_0.0.11_linux_arm64/apko]: signature not found in transparency log
```
We can verify the image signature:
```
$ COSIGN_EXPERIMENTAL=true cosign verify ghcr.io/mattmoor/apko:v0.0.11@sha256:7c29ab9bfadeff2367c298d99e8c27479823bdee114265f64beceb7547156753 | jq .
Verification for …
```
=> Add goreleaser and ko build

.gitignore, .goreleaser.yaml
- update gorelease to use the sign step to sign the build artifacts
rehearsal: https://github.com/cpanato/apko/releases/tag/v99.99.99
my question is we will distribute the tar.gz it is not easier just the binary? otherwise, the user needs to download and unpack it just to get one file (besides the license)
follow up of https://github.com/chainguard-dev/apko/pull/15/files
cc @kaniini @mattmoor
=> update gorelease to use the sign step to sign the build artifacts

go.mod, pkg/build/apk.go, pkg/build/apk_test.go
This commit introduces a new function to read the system keyring by default instead of always requiring the user to specify it in the config file.  The purpose is to have keyring defaults that allow apko to adapt to its builder.
If the configuration file defines a set of keys, these will be used as the image keyring. If no keys are specified, apko will now try to find a key set from the building environment (currently just `/etc/apk/keys/`).
/cc @kaniini 
=> Read system keyring if not specified in config file

go.mod, go.sum, pkg/build/apk.go
Add support for fetching an APK keyring via https.  Closes #27.
=> fetch APK keyring via https

go.mod, pkg/build/apk.go
I've replaced concats with `filepath.Join()` since it's used in other places throughout project
Signed-off-by: panekj <me@panekj.dev>
=> Small nitpicks

pkg/build/build.go, pkg/build/types/image_configuration.go
Using https://github.com/distroless/alpine-base/blob/557cec6bd879f417e9fe781220218d684b592c85/.apko.yaml#L1-L6
Before:
```
2022/03/04 15:28:57 build context:                                                                                                                                                     
2022/03/04 15:28:57   image configuration: {{[http://dl-cdn.alpinelinux.org/alpine/edge/main] [] [alpine-base busybox-ifupdown]} {  map[]} { [] []}}
2022/03/04 15:28:57   working directory: /tmp/apko-1603924079
2022/03/04 15:28:57   tarball path:
```
After:
```
2022/03/04 15:28:57 build context:
2022/03/04 15:28:57   working directory: /tmp/apko-3530778821
2022/03/04 15:28:57   tarball path:
2022/03/04 15:28:57   use proot: false
2022/03/04 15:28:57 image configuration:
2022/03/04 …
```
=> refactor: more verbose image configuration summary

pkg/build/image_builder.go
also add missing error message for errors returned by `normalizeApkScriptsTar`
=> refactor: parallelize more tasks in BuildImage

pkg/build/build.go, pkg/cli/build-minirootfs.go, pkg/cli/build.go, pkg/cli/publish.go
comments are using the godoc convention so they should appear on https://pkg.go.dev/.
A new function (`New`) was added to provide a consistent way of creating a build contex (should help with https://github.com/chainguard-dev/apko/issues/46)
Finally, `SOURCE_DATE_EPOCH` is no longer ignored if you don't pass a `WithBuildDate` option (that should be consistent with the spec).
=> refactor: add build.New and proper documentation to build options

pkg/build/accounts.go, pkg/build/apk.go, pkg/build/build.go, pkg/build/image_builder.go, pkg/build/oci/oci.go, pkg/build/supervision_tree.go, pkg/build/types/image_configuration.go, pkg/cli/build.go, pkg/cli/publish.go, pkg/passwd/group.go, pkg/passwd/group_test.go, pkg/passwd/passwd.go, pkg/passwd/passwd_test.go, pkg/tarball/tarball.go
By keeping errs inside the scope of an if check, fewer errant errs end
up escaping to other calls, which reduces inadvertant shadowing, and
can make it clearer to readers that the err is only considerd during
that if check.
---
If y'all don't prefer this form, that's totally fine. I won't take it personally.
=> style: Prefer if-err style wherever possible

pkg/build/accounts.go
Related https://github.com/chainguard-dev/apko/issues/71  
This should fix that particular scenario but the error can still be reproduced by adding a UID/GID.
=> refactor: skip user/group mutation if there are no accounts

go.mod, go.sum, pkg/build/build.go, pkg/build/image_builder.go, pkg/build/validate.go, pkg/cli/build.go
Add support for assertions to check the result of the build context.  
As an example, two assertions are added to check whether `/etc/passwd` and `/etc/group` are (optionally) present.
=> feat: introduce build assertions and validate passwd and group files

pkg/build/build.go, pkg/tarball/tarball.go
This makes the tarball building package more generic, allowing it to be reused in Melange.
=> refactor tarball for Melange

config/task.yaml, examples/alpine-base-rootless.yaml, examples/alpine-base.yaml, examples/nginx.yaml, go.mod, pkg/build/apk.go, pkg/build/build.go, pkg/build/oci/oci.go, pkg/build/types/types.go, pkg/build/types/types_test.go, pkg/cli/build-minirootfs.go, pkg/cli/build.go, pkg/cli/publish.go
`apko publish` produces a multiarch image index. By default, this includes six common archs, which can be overridden with `archs:` in the image config YAML, or values in the `--arch` flag (in increasing order of preference).
An attempt is made to accept both apk-style arch strings ("x86_86") and OCI-style arch strings ("amd64"), but more could probably be done. There's a TODO to support armv7 and armhf (arm/v7 and arm/v6 respectively, in OCI terms).
apk keys are extracted from arch-specific locations (e.g., `/usr/share/apk/keys/s390x/*`) and placed in the standard location (`/etc/apk/keys/*`).
`apko build` and `apko build-minirootfs` both only produce a single arch's tarball, for the current runtime arch. If the image config specifies archs in this case, a warning is logged to avoid …
=> Multiarch support

pkg/build/oci/oci.go, pkg/build/types/types.go, pkg/build/types/types_test.go, pkg/cli/publish.go
This turned out to be a little more complicated than I wanted, since the image's config doesn't include the CPU variant. So instead, I just pass through a `map[types.Architecture]v1.Image` to `PublishIndex` (which I also don't super love).
Ideas welcome. I'm also fine just punting on this if we think we'll come up with a better idea later. I don't really think it needs to block anything.
edit: An example image built with this change:
```
index.docker.io/imjasonh/alpine-multi@sha256:735bfedcd7f5e4c7a4655a7d8d23c218e837aa0290c045019270a61fcc0e184a
```
=> Include arm v6 and v7 in multiarch support

pkg/build/validate.go
Before this change, whenever I ran "apko build" I got this error:
Error: failed to build layer image: 2 errors occurred:
* /etc/passwd file is missing: %!w(<nil>)
* /etc/group file is missing: %!w(<nil>)
The problem is that "optional" was not true, so the code branch that
returned the wrapped error would always be followed even when err == nil.
Signed-off-by: Erik Sipsma <erik@sipsma.dev>
=> Fix validate passwd/group logic.

pkg/build/apk.go
using `uri.New()` on a https url returns paths such as
file:///https:/alpinelinux.org/keys/foo.pub
=> fix handling of https key paths

pkg/tarball/tarball.go
This is needed to ensure apk3 can process APKv2 packages generated by Melange.
=> pkg/tarball: add support for apk-tools file checksums

pkg/build/apk.go, pkg/build/executor.go, pkg/build/image_builder.go
Previously we just never ran scripts if we were using proot.  Instead, just never run scripts.
Also allow ExecuteChroot() to work if proot is not requested, by using `chroot` instead.  In this scenario, we assume that the build is privileged.
=> apko: never run scripts, ever

pkg/build/apk.go, pkg/build/build.go, pkg/cli/build.go
This PR introduces the `--keyring-append` flag (shorthand -k).
Using this option, new keys can be passed to apko to include in the
image keyring in addition to the keys read in the config file or from the
system keys.
=> Add --keyring-append option

pkg/cli/build.go
Fix a bug introduced in #97 where the cli is passing the wrong var to the keyring
=> Fix buf cli passing correct extrakeys

pkg/tarball/write.go
got lost in the previous PR, my apologies.
On a side note: should this and other APK specific code be moved to melange ? Right now the tarball package serves two different purposes: generating OCI layer tarball and generating APK packages.
=> fix: readd skipclose option

pkg/build/types/image_configuration.go
Before:
```
2022/03/13 00:00:49   accounts:
2022/03/13 00:00:49     runas:  nonroot
2022/03/13 00:00:49     users:  [{nonroot 10000 0}]
2022/03/13 00:00:49     groups: [{nonroot 10000 []}]
```
After:
```
2022/03/13 20:55:47   accounts:
2022/03/13 20:55:47     runas:  nonroot
2022/03/13 20:55:47     users:
2022/03/13 20:55:47       - uid=10000(nonroot) gid=0
2022/03/13 20:55:47     groups:
2022/03/13 20:55:47       - gid=10000(nonroot) members=[]
```
=> refactor: improve accounts summary

.golangci.yml, go.mod, pkg/build/types/types_test.go, pkg/passwd/group_test.go, pkg/passwd/passwd_test.go, pkg/sbom/generator/spdx/spdx_test.go
tests are using `go-cmp`, `testify` and `t.Error`.
This standardize the assertions to use testify and forbids the other two
```release-note
-Test assertions are now standardized the to use testify
```
=> test: use testify consistently

.gitignore
`make golangci-lint` installs golangci in the bin/ directory. This should avoid adding noise to the git status/diff
=> build: add bin/ to gitignore

pkg/build/apk.go, pkg/build/build.go, pkg/build/image_builder.go, pkg/exec/cmd.go, pkg/exec/exec.go
executor and `build.Context` are tightly coupled. This PR should make it easier to run a command (just create an executor and you're good) without changing api/behaviour of `build.Context`
=> refactor: decouple executor from build context

pkg/build/build.go
`build.New` should return a valid context with proper defaults
=> fix: add default arch when creating a build context

Makefile
Currently the first line in checkfmt is tab indented, however the second
and third lines are space indented, this causes the commands to not be
scoped under `checkfmt`.
Running make with any (or indeed no) target, causes the shell/sub-shell
commands to execute e.g.
```
$ make
/bin/sh: goimports: command not found
apko                            Builds apko
checkfmt                        Check formatting of all go files
clean                           Clean the workspace
fmt                             Format all go files
help                            Display help
install                         Builds and moves apko into BINDIR (default /usr/bin)
ko                              Build images using ko
ko-apply                        Build the image and apply the manifests
ko-local …
```
=> Makefile - correct indentation in checkfmt

README.md, mac/README.md, mac/lima/apko-playground.yaml
Add a new mac/ directory containing instructions for how to get up-and-running with apko on a mac, considering it is not directly supported yet.
This includes a configuration file for Lima, which creates a QEMU-based VM with the latest version of apko installed from the Alpine edge repo.
Resolves #111
=> Add Lima config and instructions for mac

pkg/build/build.go, pkg/build/oci/oci.go, pkg/build/types/types.go, pkg/cli/build-minirootfs.go, pkg/cli/build.go, pkg/sbom/generator/cyclonedx/cyclonedx.go, pkg/sbom/generator/spdx/spdx.go
Followup from https://github.com/chainguard-dev/apko/pull/118#discussion_r829500559
cc @kaniini 
Changing `type Architecture string` -> `type Architecture struct { s string }` should prevent folks from naively trying to cast a `string` to an `Architecture`, and funnel folks toward `types.ParseArchitecture`.
=> Split out types.ParseArchitecture and use it in build code

.github/workflows/release.yaml, pkg/cli/commands.go
This uses code exported from `crane auth login`, also used by `ko
login`, to simulate `docker login`, without requiring Docker to be
installed.
=> feat: Add apko login

config/task.yaml
This matches what we have been using in `github.com/distroless`
=> Change the default config name in the Tekton task

pkg/build/build.go, pkg/cli/build-minirootfs.go, pkg/cli/build.go
Needed to fix `apko build` command when no explicit `--build-arch` is requested.
Closes #126.
=> fix up early logging and build context for early builds

pkg/build/oci/oci.go
Unfortunately `empty.Image` defaults to setting the Docker "schema2" media type, but `empty.Index` defaults to no media type.  This is unfortunate because Docker requires media types, so the absence of a media type is interpreted as OCI, and gcr.io doesn't allow mixing OCI index types with Docker image types.
When using `ghcr.io/distroless/static` with `ko` multi-arch I see:
```
MANIFEST_INVALID: Failed to parse manifest for request "/v2/.../manifests/latest": Image index child manifest not supported: application/vnd.docker.distribution.manifest.v2+json.
```
=> Set the `mediaType` on the index.

examples/alpine-base-rootless.yaml, examples/alpine-base.yaml, examples/nginx-rootless.yaml, examples/nginx.yaml, pkg/build/oci/oci.go, pkg/build/types/types.go
Adds environment stanza to image configuration:
```yaml
environment:
PATH: ...
```
A default environment is provided for images which do not have one.
Closes #136.
=> configurable image environment

pkg/tarball/write.go
When building images with hardlinks, we previously copied the file multiple times.  This deduplicates the hardlinks, bringing [this git-init image](https://github.com/mattmoor/git-init) down to 15MiB instead of hundreds.
=> bugfix: archive hardlinks

pkg/build/oci/oci.go
Closes: #128
Signed-off-by: Ariadne Conill <ariadne@chainguard.dev>
=> oci: set created field correctly in config

.gitignore, CONTRIBUTING.md, examples/apko-devenv.yaml, hack/make-devenv.sh
This PR adds a shell script that allows a one-command way to start an apko development environment. 
Running the following script from the top of the apko repo launches a series of steps that use apko itself to build an image and drop the user into a development shell:
```
./hack/make-devenv.sh 
```
The environment is pre loaded with some tools (currently go, git and jq) and the user shell is opened with the apko repository mounted, ready to run any changes you make in your editor. I've also added a first draft of a CONTRIBUTING.md doc with instructions to launch the shell and basic info for contributors.
The image is `apko-inception` because apko is building the apko environment with a script that calls itself multiple times :)
=> apko development environment

examples/alpine-386_amd64.yaml, examples/alpine-amd64.yaml, pkg/build/types/types.go, pkg/cli/publish.go
There appears to be 2 issues with the current `archs` support from the config file.
1.
Currently if you try and specify the `archs` option in the config file,
the publish command fails along the lines of
```
line 7: cannot unmarshal !!int `386` into types.Architecture
line 7: cannot unmarshal !!str `amd64` into types.Architecture
```
Add a custom `UnmarshalYAML` function to `Architecture`, supporting
decoding the string values into the correct `Architecture` object.
2.
Currently if we specify 1 arch under `bc.ImageConfiguration.Archs`, the
publish command will handle it, however if we have more than 1 the
default case uses `archs`, which is defaulted to all entries (cli
options).
Swap out the default range case to use `bc.ImageConfiguration.Archs`,
which will be set to `archs` in the …
=> Fix config `archs` support

examples/alpine-slim.yaml, pkg/build/build_implementation.go, pkg/build/buildfakes/fake_build_implementation.go, pkg/build/os-release.go, pkg/build/types/image_configuration.go, pkg/build/types/types.go
Generate `/etc/os-release` if it does not already exist.
Closes #165.
=> /etc/os-release generator

examples/apko-devenv.yaml
Requires `shell-fragment` syntax.
=> Fix development environment apko example

docs/apko_file.md, examples/alpine-386_amd64.yaml, examples/alpine-amd64.yaml, examples/alpine-base-rootless.yaml, examples/alpine-base.yaml, examples/alpine-slim.yaml, pkg/build/oci/oci.go, pkg/build/types/image_configuration.go, pkg/build/types/types.go
Allowing entrypoint to be blank can be used to force default docker behaviour of running cmd in shell. Also updated examples.
Closes #177.
We could also create a PR to set CMD to `/bin/sh -l` which would be keep previous behaviour when no command is specified.
=> Allow entrypoint to be blank.

pkg/build/accounts.go
Previously we did a `MkdirAll` with `0700` as `root` and `Chown` the top directory to the appropriate `uid:gid`, but it turns out that this means `/home` is owned by `root` with 0700 which is insufficient for non-`root` users to list directories under `/home/...`
Instead, we lead the `MkdirAll` with 0755 that was our fallback, but in addition to the `Chown` we do a `Chmod` to reduce just the leaf directory's permissions to `0700`, which appears to work, and matches the `/home` permissions from the OG distroless images.
=> Try again fixing the permissions on home directories.

.github/workflows/add-issues.yml
Adding Github action to automatically add apko issues to Github Projects Beta board.
https://github.com/orgs/chainguard-dev/projects/12
=> Github action to automatically add apko issues to project board.

internal/cli/build.go, internal/cli/publish.go, pkg/build/oci/oci.go, pkg/build/options.go, pkg/options/options.go
Resolves #209
It works! After running:
```
$ apko publish --use-oci-mediatypes examples/alpine-base.yaml ghcr.io/jdolitsky/apko-oci-test:testing1234
```
Here is the results:
```
$ crane manifest ghcr.io/jdolitsky/apko-oci-test:testing1234 | jq
```
```json
{
"schemaVersion": 2,
"mediaType": "application/vnd.oci.image.index.v1+json",
"manifests": [
{
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"size": 405,
"digest": "sha256:ac9c79faea9a6d47ef0e81fd69769ac8c9627fa5d0fcf41bdd42d004c16128f8",
"platform": {
"architecture": "386",
"os": "linux"
}
},
{
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"size": 405,
"digest": "sha256:4adff1fc78d9a05767aa15b8e3f67b1eccb965af9c38662e5b1d4d3ff909803d",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": …
```
=> Add --use-oci-mediatypes option to use OCI mediatypes

internal/cli/build.go, internal/cli/publish.go, pkg/build/oci/oci.go, pkg/build/options.go, pkg/options/options.go
Resolves #211
This reverses the unreleased `--use-oci-mediatypes` option and replaces it with `--use-docker-mediatypes`
=> Use OCI mediatypes by default

pkg/build/build_implementation.go, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/options/options.go
This ensures the SPDX SBOM `creationInfo` is consistent with the `SourceDateEpoch` setting.
Closes #208.
=> fix creation dates on SPDX SBOMs

pkg/build/oci/oci.go, pkg/sbom/generator/generator.go, pkg/sbom/generator/idb/idb.go
The apkdb can be used as an SBOM itself (in fact, our other SBOMs are just reinterpretations of this data anyway).  By doing so, we can enable use of the `apk audit` command to check for runtime deviations in a container.
Right now this is not terribly useful for :sparkles: political reasons :sparkles:.  We will need to adjust something related to OCI and SBOMs (I forget what) to allow for upload of multiple SBOM types to make the most of this capability.
Closes #187.
=> add support for uploading an IDB file as an SBOM

.github/workflows/mink-e2e.yaml, .github/workflows/release.yaml
This should hopefully fix our Fulcio issue e.g., https://github.com/chainguard-dev/apko/runs/6710222241?check_suite_focus=true#step:7:112
=> chore: bump cosign-installer to v2.3.0, which installs cosign 1.8.0

hack/make-devenv.sh
dash does not support the &>/dev/null shorthand.
=> hack/make-devenv: fix compatibility with dash

go.mod, go.sum, pkg/build/oci/oci.go
This PR implements a backoff timer for GGCR remote operations which should hopefully reduce the number of publish failures we have when github container registry flakes out.
We might want the ability to override the default backoff policy, but it seems reasonable enough for now.
=> implement backoff for GGCR remote operations

pkg/build/types/types.go, pkg/build/types/types_test.go
Followup from https://github.com/chainguard-dev/apko/pull/249
I'm not totally happy with this either, tbh. With this, `--arch=arm64,all` will just fail mysteriously later when there aren't apks for the `"all"` arch.
Maybe we should just fail if `all` is found outside of the only element, but that means letting `ParseArchitectures` return an err, which makes this change a lot bigger.
I'd also be okay just closing this and allowing `--arch=foo,bar,all`
=> Accept --arch=all only if it's the only element

pkg/s6/supervision_tree.go
this allows rootless images to make use of the supervisor
closes #240
=> s6: change supervision tree permission to 0777 from 0755

internal/cli/build.go, internal/cli/publish.go, pkg/build/build.go, pkg/build/build_implementation.go, pkg/build/build_test.go, pkg/build/oci/oci.go, pkg/options/options.go, pkg/sbom/generator/cyclonedx/cyclonedx.go, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/options/options.go
This PR implements proper image structure in the individual apko images. Both CycloneDX and SPDX have been updated to capture the structure of the images. The biggest change is when running `apko publish`:
* When running apko publish and generating a Cyclonedx SBOM, the layer is now a subcomponent of a new image component.
* When requesting an SPDX SBOM the image now has its own top level package and is related to the layer package.
It is a big refactor as the SBOM generation is now done after publishing the images and the SBOM is now attached at the end of the publish function.
Easiest to visualize it by looking at the sboms. This is before the change:
This is after the change:
There are other minor changes, each commit captures the changes as atomic as I could.
Fixes …
=> Fix image structure in apko SBOMs

README.md
Breaking out installation would, IMO, have accelerated my timeline to running and using `apko`.
I suspect there are additional ways to install `apko` and that might be worth calling out.
Additionally, I suspect there are additional steps here that likely need to be spelled out explicitly. Do mac users need other software to be installed and/or running for this hack script to perform as expected?
=> Add installation instructions before quickstart

pkg/sbom/generator/cyclonedx/cyclonedx.go
Package references in the CycloneDX SBOMs are wrong and dependecies of one package are pointing to itself. This PR fixes it.
=> Fix dependency refs in CycloneDX sboms

pkg/exec/exec.go
This makes the preflight check for building packages with Melange on Ubuntu hosts more clear.
=> exec: check for debian qemu-user-static binaries as well as the alpine ones

internal/cli/publish.go, pkg/build/oci/oci.go
This PR fixes a crash when publishing a single arch image where apko would try to write an index SBOM when no index was published.
Fixes crash in: https://github.com/distroless/nginx/runs/7205393317?check_suite_focus=true#step:7:721
=> Fix crash when publishing single arch image

.github/workflows/mink-e2e.yaml
This PR modifies the SBOM mink e2e task to check for the existence of an SBOM at the multiarch index to ensure the current build always publishes one.
=> mink-e2e: Ensure index SBOM is built

internal/cli/build.go
at this time, `apko build` produces an OCI image bundle which can be loaded into a local docker instance (via `docker load`), and this does not make any sense to support multi-arch here.
later we can refactor this to split out multiple layers, but right now it causes problems for pre-submit checks that are multiarch :)
=> build: silently drop other archs when a multi-arch build is requested

Makefile
CVE-2022-24765 makes it difficult to rebuild from a git
repository as another user, therefore do not bother trying
to do it.
=> make install: skip rebuilding apko

internal/cli/publish.go, pkg/build/oci/oci.go
This PR fixes two nits leftover from the review of https://github.com/chainguard-dev/apko/pull/257
* Removes a comment to reenable the clean-up of the tmpdir in `apko publish`
* Avoids returning a partially formed index when an error happens in `oci.publishTagFromIndex()`
=> Review nits from #257

pkg/sbom/generator/cyclonedx/cyclonedx.go
This PR implements the CycloneDX index SBOM generation following the same structure we're using for SPDX.
```json
{
"bomFormat": "CycloneDX",
"specVersion": "1.4",
"version": 1,
"components": [
{
"bom-ref": "pkg:oci/apko-test?mediaType=application%2Fvnd.oci.image.index.v1+json",
"type": "container",
"name": "apko-test@sha256:1638f8d567670cdc9fdb094ed177933cdff76eaf98d17097da2d8bed418c5fe1",
"version": "1638f8d567670cdc9fdb094ed177933cdff76eaf98d17097da2d8bed418c5fe1",
"description": "Multi-arch image index",
"purl": "pkg:oci/apko-test?mediaType=application%2Fvnd.oci.image.index.v1+json",
"hashes": [
{
"alg": "SHA-256",
"content": "1638f8d567670cdc9fdb094ed177933cdff76eaf98d17097da2d8bed418c5fe1"
}
],
"components": [
{
"bom-ref": "pkg:oci/apko-test@sha256:58dfecc2f53c99406ea5dd0dd706481569a …
```
=> Implement CycloneDX index SBOM generation

pkg/build/paths.go, pkg/build/types/types.go
For distroless.dev/nginx, the `/var/lib/nginx` and `/run/nginx` directories need to be writable by the nginx process.
Right now, there are at least 6 subdirectories/files that also need updated permissions.
We could write each one out explicitly in apko.yaml, but I think it would be easier to give people the option
to change permissions on a directory and all subdirectories/files.
This way we just have to explicitly call out the two dirs mentions above and set `recursive: true` e.g.
```yaml
- path: /var/lib/nginx
uid: 10000
gid: 10000
type: directory
permissions: 0o755
recursive: true
- path: /run/nginx
uid: 10000
gid: 10000
type: directory
permissions: 0o755
recursive: true
```
=> Add recursive option to PathMutation to traverse directory and modify perms

pkg/build/build_implementation.go, pkg/sbom/generator/cyclonedx/cyclonedx.go, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/options/options.go
This PR adds the VCS URLs to the SBOMs as external references. Both standards are implemented as follows:
```json
"externalReferences": [
{
"url": "vcs",
"type": "git+ssh://git@github.com/puerco/apko.git"
}
],
```
```json
"externalRefs": [
{
"referenceCategory": "PACKAGE_MANAGER",
"referenceLocator": "pkg:oci/apko-test?mediaType=application%2Fvnd.oci.image.index.v1+json\u0026tag=latest",
"referenceType": "purl"
},
{
"referenceCategory": "OTHER",
"referenceLocator": "git+ssh://git@github.com/puerco/apko.git",
"referenceType": "vcs"
}
]
```
/cc @kaniini
=> Add VCS URL to SBOMs

pkg/build/build_implementation.go, pkg/sbom/generator/cyclonedx/cyclonedx.go, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/options/options.go
This PR adds  media types to the SBOMs of all the indexes, layers and images. It honors the `UseDockerMediaTypes` and uses new functions shared by the SPDX and CycloneDX implementations.
/cc @kaniini @mattmoor
=> Add MediaTypes to purls of all images and layers

internal/cli/build.go, internal/cli/publish.go, pkg/build/build.go, pkg/build/options.go, pkg/build/types/image_configuration.go, pkg/options/options.go, pkg/vcs/vcs.go
Address concerns based on over-the-weekend testing of the VCS URL feature:
- sanitize authentication data from the generated VCS URLs
- add ability to disable VCS URL probing outside of setting one explicitly in the config
=> improve VCS URL detection and add opt-out

pkg/sbom/generator/cyclonedx/cyclonedx.go, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/options/options.go
This commit adds a parser to the name returned by `RepositoryStr()` to return as the purl image name only the last part when several slashes are in the name. We now have a specific function in options to craft the purl name of the index.
The same commit also reuses the index function in the SPDX and CycloneDX implementations.
The previous purl names will now change to be as expected:
From: `pkg:oci/distroless%2Fstatic@sha256:ed7854ed`
To: `pkg:oci/static@sha256:ed7854ed`
=> Simplify purl index/image names, abstract to function

pkg/sbom/generator/cyclonedx/cyclonedx.go
This PR fixes a bug where the VCS external reference fields
where inverted in the CycloneDX implementation
=> CycloneDX: Update inverted fields in VCS externalRef

pkg/build/accounts.go
```
accounts:
run-as: nonroot
```
now automatically becomes
```
accounts:
run-as: 65532
```
closes #129
=> accounts: resolve non-UID run-as users to their UIDs

pkg/sbom/options/options.go
We discovered a bug in the purl go module. There is a PR in flight to fix
it: https://github.com/package-url/packageurl-go/pull/22 but, while it merges,
(the PR has been open since 2020) we need to escape plus signs manually
to encode the purl query strings correctly.
This PR adds that manual escaping to the purl qualifier values. Sample:
```json
"purl": "pkg:oci/static@sha256:42962ba12d91b05a43ea33985c7cf8103b46de27da044790cbcccaebc97f37c4?arch=amd64&mediaType=application%2Fvnd.oci.image.manifest.v1%2526json&os=linux",
```
Fixes https://github.com/chainguard-dev/apko/issues/292 temporarily
/cc @kaniini @mattmoor 
=> Escape plus signs in purl qualifiers

internal/cli/publish.go, pkg/build/oci/oci.go
We now tag and emit references into the refs file for all arch images to help external
tools know what we've built (for example to sign  them).
Closes: https://github.com/chainguard-dev/apko/issues/288
/cc @mattmoor 
=> Tag and omit references to the refs file

internal/cli/publish.go, pkg/build/oci/oci.go, pkg/build/options.go, pkg/build/types/image_configuration.go, pkg/build/types/types.go
This PR adds support for annotating apko images with a new flag `--annotations`. Example:
```
apko publish --annotations="org.chainguard.made:True" --arch=amd64 \
examples/nginx-rootless.yaml 172.17.0.1:5000/apko-test/nginx
crane manifest 172.17.0.1:5000/apko-test/nginx@sha256:5e870632a8a833251888a811c798e4595759aa60a0e379d788509410705e8ebe | jq .annotations
{
"org.chainguard.made": "True"
}
```
=> Support OCI annotations in apko publish w/ --annotations

internal/cli/publish.go
This commits wraps the image list writes in a mutex to lock it when processing architectures.
Fixes panic when attempting concurrent writes to the images map.
/cc @imjasonh 
=> publish: Lock img list w/mutex before writing

README.md, mac/README.md
Points users to Docker image before hack scripts/Lima.
Signed-off-by: Adrian Mouat <adrian@chainguard.dev>
=> Update usage instructions.

pkg/sbom/generator/spdx/spdx.go
This commit adds the required types and fields to the SPDX SBOM
generator needed to support files and not just packages.
/cc @kaniini @jdolitsky 
=> Add SPDX File support

pkg/sbom/generator/spdx/spdx.go
This commit moves the VCS URL obtained from the image config repository to the `DownloadLocation` field of the main package representing the artifact being built (image or index).
This change makes the apko sboms a little better in following what the spec recommends and aligns them with some of the prevailing practices.
=> spdx: Move VCS URL to DownloadLocation

pkg/vcs/vcs.go, pkg/vcs/vcs_unit_test.go
This pull request adds the commit hash to the VCS URLs in the SBOMs. It is a bit big because there are some extras:
1. The logic to open repos, get the repository URLs and the the new function to commit hashes has been refactored to new utility functions which are easier to unit test while leaving the main vcs package in a better shape if we want to move it to a fakeable implementation if it gets more complex.
2. Unit tests for those functions are also included. The tests embed a test empty repository to test some of the git functions
The VCS URLs are compliant with the SPDX download locators:
`git+ssh://github.com/puerco/apko.git@2518d013269528b3b6956b9b9a984353d7bb1f4f`
=> Add commit hash to VCS URLs 

pkg/build/oci/oci.go
We are currently adding a `org.opencontainers.image.source` label with the VCS URL to the image config. This commit adds the annotation to the manifest of the single arch images. Sample:
`crane manifest 172.17.0.1:5000/apko-tests/alpine@sha256:23d583... `
```json
{
"schemaVersion": 2,
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"config": {
"mediaType": "application/vnd.oci.image.config.v1+json",
"size": 642,
"digest": "sha256:e304ce658035348bdd7b6748f9cb54fd4a28f0267fce1f57ae878953b4c0124d"
},
"layers": [
{
"mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
"size": 3802370,
"digest": "sha256:6770200400756823915c9e1bb0f8ffd2feff37517ecaa27234f4f9b52e9248ca"
}
],
"annotations": {
"org.opencontainers.image.source": …
```
=> Add org.opencontainers.image.source image annotation

pkg/build/oci/oci.go
PR https://github.com/chainguard-dev/apko/pull/322 appears to have introduced an panic error on the canary image:
```
panic: assignment to entry in nil map
goroutine 1 [running]:
chainguard.dev/apko/pkg/build/oci.buildImageFromLayerWithMediaType({_, _}, {_, _}, {{{0xc00038b9b0, 0x3, 0x3}, {0x0, 0x0, 0x0}, ...}, ...}, ...)
chainguard.dev/apko/pkg/build/oci/oci.go:109 +0xbf5
chainguard.dev/apko/pkg/build/oci.buildImageTarballFromLayerWithMediaType({_, _}, {_, _}, {_, _}, {_, _}, {{{0xc00038b9b0, 0x3, ...}, ...}, ...}, ...)
chainguard.dev/apko/pkg/build/oci/oci.go:285 +0x2d3
chainguard.dev/apko/pkg/build/oci.BuildImageTarballFromLayer({_, _}, {_, _}, {_, _}, {{{0xc00038b9b0, 0x3, 0x3}, {0x0, ...}, ...}, ...}, ...)
chainguard.dev/apko/pkg/build/oci/oci.go:280 +0x179 …
```
=> Fix nil map assingment for annotations

pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/spdx_test.go
This commit modifies the SPDX package to describe the source code that built the images in a new package. This package is generated from the VCS URL whenever `apko` is able to find it.
For reference the SBOMs now have the structures:
=> Add reference to image build code in new package

pkg/build/types/types.go
This adds a useful creature comfort for building images which will only be used internally and will only support the host architecture.
=> types: add host alias for ParseArchitecture

pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/spdx_test.go
This commit updates the `spdx.addSourcePackage()` function to add a purl to the generated package representing the source code.
```release-note
The SPDX package representing the source code now includes a purl of type `github` if the URL is a GitHub repository
```
=> Add purls to VCS source package

pkg/vfs/dirfs.go, pkg/vfs/dirfs_unit_test.go, pkg/vfs/testdata/etc/motd, pkg/vfs/vfs.go, pkg/vfs/vfs_unit_test.go
The VFS package provides an overlay filesystem, where files are physically backed by an underlay filesystem, but permission and ownership are tracked by the VFS itself.  This allows for `Chown` and `Chmod` operations to work without requiring root.
=> VFS core (for rootless apko)

pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/spdx_test.go
This PR changes apko to start generating SBOMs
conforming to the 2.3 SPDX spec. We now use the new
2.3 package purpose field to add hints to the source
code and images packages.
=> SPDX 2.3 support!

pkg/build/build_implementation.go
this is necessary on alpine ldconfig
resolves flakes on distroless/alpine-base image which has ldconfig
=> run ldconfig after busybox symlinks are installed

pkg/exec/implementation.go
otherwise, this can cause synchronization errors on sufficiently
parallel machines, like a threadripper
=> exec: wait for monitorPipe to finish before finalizing the task

internal/cli/publish.go, pkg/apk/apk.go, pkg/build/options.go, pkg/options/options.go
This is necessary to add a suffix to the generated version tags, e.g. `foo:1.2.3-glibc` instead of just `foo:1.2.3`.
=> Add --tag-suffix to apko publish command.

pkg/build/oci/oci.go
This makes a small tweak to how we populate the `architecture` and `variant` fields in the image config, such that when the user builds images for architectures with variants (e.g. `arm/v7`), the image we produce is compliant with the [OCI spec for image configs](https://github.com/opencontainers/image-spec/blob/main/image-index.md#platform-variants).
This also may resolve an issue where Grype was unable to scan apko images that used architecture variants (reported as https://github.com/anchore/grype/issues/831).
If anyone can help point me toward a good way to add an automated test here, I'd greatly appreciate it!  🙏 😃 
We can perform these steps first on the **"before"** (broken) state, and then on the **"after"** state to see the expected adjustment to behavior...
(I'm on an M1 Mac w/ …
=> Use OCI arch and variant for image config

pkg/build/os-release.go
Previously, non-alpine distributions, such as Wolfi, may have an erroneous `/etc/alpine-release` file that shouldn't be there.
Before (with Trivy):
After (with Trivy):
Trivy no longer detects a Wolfi image as an Alpine one, as intended.
=> postpone generating vendor release file until after generating os-release

pkg/build/oci/oci.go
https://github.com/chainguard-dev/apko/pull/353 added a call to `mutate.Annotations(signedIndex, map[...]).(oci.SignedIndex)`, which panics because the type that comes out of `mutate.Annotations` doesn't implement `oci.SignedIndex`, only ggcr's `v1.ImageIndex`.
Example: https://github.com/chainguard-images/template/actions/runs/3153995862/jobs/5131103522#step:5:972
Just replace this with a TODO for now, since the solution is to reimplement `mutate.Annotations` in cosign (bleh) and that will take a minute. Nobody missed not having annotations on the indexes anyway.
As far as I know, the annotations added to images are just fine.
=> fix: don't annotate indexes, this panics

.ko.yaml, Makefile, README.md, mac/README.md
- distroless.dev -> cgr.dev/chainguard
- github.com/distroless -> github.com/chainguard-images
- remove an unused reference to gcr.io/distroless
=> update references to distroless

pkg/sbom/options/options.go
We had been manually escaping qualifiers until purl fixed this upstream. It looks like the upstream fix landed, so now we're double-escaping, which breaks some parsing.
cc @eddiezane @mattmoor
=> don't double-escape purl qualifiers

pkg/sbom/options/options.go, pkg/sbom/options/options_test.go
This PR fixes a bug in the format of purl qualifiers and introduces a unit test to check the key value string and the encoding
=> FIx purl qualifier encoder bug, add unit test

pkg/build/types/types.go
This is needed for Melange's `${{host.triplet.gnu}}` and `${{host.triplet.rust}}` support.
=> add GNU and Rust triplets to Architecture type

pkg/sbom/generator/spdx/spdx.go
This commit fixes an invalid SPDX identifier on in the VCS package. Thanks for investigating it Dan!
/cc @luhring 
=> FIX VCS package SPDX identifier

.golangci.yml, header.tmpl
An update to the goheader header.tmpl to support any whitespace before the apache URL; some editors change the format and it fails on tab vs space vs 2 space vs space+tab vs I have no idea what. This makes it much more tolerant.
=> more flexible header template

pkg/sbom/generator/spdx/spdx.go
This PR aims to simplify SBOMs by omitting from the JSON output the SDPX elements with a cardinality of 0. Now updated for SPDX 2.3.
=> omitempty SBOM elements with 0 cardinality

internal/cli/publish.go
If an image index is nil when attaching the SBOM, skip attaching it
Tries to fix https://github.com/chainguard-dev/base-image-rumble/issues/214
/cc @jdolitsky @jspeed-meyers 
Signed-off-by: Adolfo Garcia Veytia (puerco) <puerco@chainguard.dev>
=> Dont attach SBOM if index is nil

docs/sbom-composition.md
This PR adds a document detailing how apko composes SBOMs found inside of apk packages.
/cc @ltagliaferri: Perhaps this document is also appropriate for edu.chainguard ?
=> Add Apko SBOM Composition Document

pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/spdx_test.go
This PR fixes two bugs in the SPDX SBOM output:
1. Our originator values were missing the type label.  Now it is set to `Person:`
2. The second commit switches the external reference type label from `PACKAGE-MANAGER` to `PACKAGE_MANAGER`, modified in SPDX 2.3.
=> Fix two bugfixes in SPDX output

internal/cli/build-minirootfs.go, internal/cli/build.go, internal/cli/publish.go, pkg/apk/apk.go, pkg/build/build_implementation.go, pkg/build/options.go, pkg/exec/cmd.go, pkg/exec/exec.go, pkg/exec/exec_test.go, pkg/options/options.go
As all image building operations are now done on a VFS, we do not need to fake any root user anymore.  So proot can die.
=> Remove proot support

pkg/apk/impl/implementation.go, pkg/apk/impl/install.go, pkg/build/build_implementation.go
With these fixes, apko should be able to build all images again without using apk-tools.
=> fix some build-breaking bugs with the native apk implementation

pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/spdx_test.go
This PR changes back the external reference category label from `PACKAGE_MANAGER` to `PACKAGE-MANAGER`. It was resolved in the SPDX tech call that both would be supported but the preferred form [is the one documented in the schema](https://github.com/spdx/spdx-spec/blob/5c893ae8010d5d972ecdf1af953a95d9f53de415/schemas/spdx-schema.json#L325): `PACKAGE-MANAGER`. Tools should support both forms now.
Schema: https://github.com/spdx/spdx-spec/blob/5c893ae8010d5d972ecdf1af953a95d9f53de415/schemas/spdx-schema.json#L325
Ref: https://github.com/spdx/tools-java/pull/76/files#diff-2d62de45a362cf43a5c97c9481212a3f8b485b8488aeea7415fb5b7b5dfc2d8cL325
This essentially reverts https://github.com/chainguard-dev/apko/pull/446 but now that the SPDX tools in java and go have been updated we should sync. …
=> Change back PACKAGE-MANAGER to PACKAGE_MANAGER

pkg/apk/impl/implementation.go, pkg/apk/impl/implementation_test.go, pkg/apk/impl/repo.go, pkg/apk/impl/repo_test.go
Fixes #464 
Issue with two problems was a regression caused by #426 
It was treating keyfiles to read when passed via `--keyring-append` as relative to workdir, which made no sense; when someone types `build --keyring-append /path/to/file`, they mean, "relative to where I am running apko".
This fixes it.
It also was doing the same for `--repository-append`; fixes that too.
=> read keyfiles from local; read local repositories

examples/alias-only.yaml, pkg/apk/impl/repo.go
Fixes #469 
It knows how to handle aliases (or provided-by) for dependencies, but not for direct packages. This fixes that. It also adds a test case using the example provided by @kaniini in #469
=> handle package that is only an alias

pkg/build/build_implementation.go
This PR fixes a bug where ReadReleaseData was not being called when generating the image SBOMs. This caused purls to be incomplete when generated for packages that don't include an SBOM. Fixed now:
```
📂 SPDX Document sbom-sha256:48f32f7b63728353062f85d42ed792f6736a61e2730043eee1c8b773d137c841
│ 
│ 📦 DESCRIBES 1 Packages
│ 
├ pkg:oci/static@sha256:9b041a3a16992f1b1409b2e4...
│  │ 🔗 2 Relationships
│  ├ CONTAINS PACKAGE pkg:oci/static@sha256:48f32f7b63728353062f85d42ed79...
│  │  │ 🔗 5 Relationships
│  │  ├ CONTAINS PACKAGE pkg:apk/alpine/alpine-baselayout-data@3.4.0-r0?arch=x86_64
│  │  ├ CONTAINS PACKAGE pkg:apk/alpine/alpine-keys@2.4-r1?arch=x86_64
│  │  ├ CONTAINS PACKAGE pkg:apk/alpine/alpine-release@3.17.0-r0?arch=x86_64
│  │  ├ CONTAINS PACKAGE …
```
=> Call ReadReleaseData() when generate img SBOM

pkg/apk/impl/fs/rwosfs.go, pkg/apk/impl/fs/rwosfs_test.go
`apko.DirFS(dir)` creates a filesystem that assumes the root `dir` is empty. Not only is that not always valid, but it conflicts with how `os.DirFS(dir)` works, which is likely to lead to unpleasant surprises.
This adds support for scanning `dir` when first invoking `apkofs.DirFS(dir)` so that you can use an existing dir.
It also adds a few basic tests to `dirFS`. We certainly could have more, but it is a start, and it covers some of the basic cases of the new functionality.
=> add DirFS support for existing filesystem

pkg/apk/impl/fs/doc.go, pkg/apk/impl/fs/memfs.go, pkg/apk/impl/fs/rwosfs.go, pkg/apk/impl/fs/rwosfs_test.go
One thing that we didn't think of earlier in, in terms of missing OS/filesystem capabilities, is case-insensitivity. apk packages are assumed to be running on Linux, where case-sensitivity is the norm. While the vast majority of packages are unlikely to use it, some will. For example, `linux-headers` does. The melange example `sshfs.yaml` triggers this by including `linux-headers`.
memfs already is case-sensitive.
This adds case-sensitivity to `dirFS`. When started, it tests the filesystem to see if it is case-insensitive, and if it is, it keeps track of sensitive-duplicate files in memory. It relies on there not being too many of them, or their being too big.
It also adds a test for it.
We may want to start thinking about a more persistent option, where `dirFS` stores _everything_ on …
=> support for case-insensitive filesystems

internal/cli/publish.go, pkg/apk/impl/fs/rwosfs.go, pkg/build/build.go, pkg/build/options.go
Fixes #492 
`build` command only builds one architecture, while `publish` builds multiple. But the workdir provided for `builder.New(workdir)` only included the root of the tempdir. That meant that when building multiple archs, they would trounce each other.
This explicitly builds in an arch-specific subdirectory, which keeps everything clean.
=> use dedicated sub directory for building each arch

pkg/apk/impl/fs/memfs.go, pkg/apk/impl/fs/rwosfs.go, pkg/apk/impl/sign.go, pkg/build/accounts.go, pkg/build/build_implementation.go, pkg/passwd/group.go, pkg/passwd/passwd.go, pkg/s6/supervision_tree.go, pkg/tarball/append.go, pkg/tarball/write.go
Fixes #497
There were several issues:
* chown and chmod were non-functional (it was one of those thing set for "later" that never got addressed)
* Uname and Gname were not being provided for the tar headers
* Uname/Gname/UID/GID override were set, which caused _everything_ to be owned by root, and thus nonrunnable
=> support chmod/chown

.github/workflows/build-samples.yml, internal/cli/build.go, pkg/build/oci/oci.go
Currently, there is a split between how `build` works and how `publish` works:
* `publish`: build all archs indicated an a yaml file, unless overridden by `--arch`
* `build`: build your local arch, unless overridden by `--build-arch`, which will only take the first arch
The problems are:
* will only build one arch, which means no way to generate an index or multiple archs
* no way to test multi-arch build without doing `publish`, which you may not want to do
* `build` always ignores the `arches` in the yaml
* inconsistent behaviour between the two
* inconsistent flags
This changes the above to make it consistent:
* same flag `--arch`
* builds for all archs in yaml, unless explicitly overrides
* supports building for multiple archs
* supports the `--arch host` for "build local"
This _is_ a …
=> build all archs indicated in a file

pkg/build/types/types.go
Without this it can be hard to programmatically construct an `ImageConfiguration` since you can't specify anything in nested anonymous structs. 
Signed-off-by: Jason Hall <jason@chainguard.dev>
=> define types for structs in ImageConfiguration

docs/apko_file.md
Signed-off-by: Paul Meyer <49727155+katexochen@users.noreply.github.com>
Took me some time to understand that `local` isn't a special value but a label and that I also need to mask the packages I want from that repo.
=> Clarify usage of local repository masking

.github/workflows/release.yaml, Makefile
previously, sboms generated by apko canary would just identify the tool version as "canary" which various SBOM scoring tools penalized
Signed-off-by: Ariadne Conill <ariadne@chainguard.dev>
=> makefile: separate image tag concern from git version identifier

internal/cli/build.go, internal/cli/publish.go
The `apko publish` and `apko build` logic for reconciling requested archs vs config archs was off. It was ignoring the CLI flags sometimes. This reconciles them.
=> correctly handle archs

pkg/apk/impl/fs/memfs.go, pkg/apk/impl/fs/memfs_test.go
Fixes the issue raised [here](https://github.com/jdolitsky/images/actions/runs/4168919915/jobs/7218972204).
Short form is that hardlinks always are treated as absolute path, and should be so inside the underlying memfs. This does the right thing with them.
=> handle hardlinks correctly

pkg/apk/impl/repo.go, pkg/apk/impl/version.go
Before, when a dependency was found not by package name, but by a provided file, we just took whichever version was first. That was inconsistent, and not the right answer anyways.
This consistently does the following:
1. If the package declaring the dependency also provides the dependency, do nothing, as we satisfy it ourselves.
2. If any of the packages providing the dependency are of the same origin `o:` as the package requesting the dependency, restrict our selection set to just those packages with a matching origin; else look in all packages providing the dependency
3. Of the packages remaining that provide the dependency (matching origin or, if none, then all), take the highest version (highest as defined by the package logic)
=> use highest version of package when found by provided files

pkg/apk/impl/repo.go
Specifically handles the case where a package provides another package, identical to others, but with a different version number
=> handle when a package provides an override for another base

internal/cli/commands.go, internal/cli/show-packages.go, pkg/apk/apk.go, pkg/apk/apk_implementation.go, pkg/apk/apk_test.go, pkg/apk/apkfakes/fake_apk_implementation.go, pkg/apk/impl/implementation.go, pkg/build/build.go, pkg/build/build_implementation.go, pkg/build/buildfakes/fake_build_implementation.go
```
apko show-packages ./file.yaml
```
Shows all of the dependencies for whichever archs are chosen. Allows to check dependency trees and packages without a full rebuild. Much faster than having to do a `build`, as it only needs to download the indexes, not all of the packages.
Also separates some calls out into their own parts to make it doable.
E.g.
```
$ apko show-packages --arch amd64,arm64 ../../chainguard-images/images/images/ko/configs/latest.apko.yaml
Feb 22 12:18:04.971 [INFO] loading config file: ../../chainguard-images/images/images/ko/configs/latest.apko.yaml
Feb 22 12:18:04.972 [INFO] [arch:aarch64] Determining packages for 2 architectures: [amd64 arm64]
Feb 22 12:18:04.972 [INFO] loading config file: ../../chainguard-images/images/images/ko/configs/latest.apko.yaml
Feb 22 …
```
=> option to show-packages

examples/options.yaml, internal/cli/build.go, internal/cli/publish.go, pkg/build/options.go, pkg/build/types/build_option.go, pkg/build/types/types.go
A typical pattern is to use a stripped down base image which does not contain anything more than necessary to support an application.  This is called "distroless" normally.  A configuration to support minimal glibc binaries might look like:
```yaml
contents:
keyring:
- https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
repositories:
- https://packages.wolfi.dev/os
packages:
- ca-certificates-bundle
- wolfi-baselayout
- glibc
- libgcc
```
However, sometimes, we would like to debug our application, which might require a shell, amongst other tools.  For this purpose, we have `-dev` and `-debug` image variants.  But right now, we are having to maintain a lot of boilerplate YAML for this.
`include` can help a bit, e.g.:
```yaml
include: minimal.yaml
contents:
packages:
- busybox
```
But this …
=> Add melange-style build options for apko images

internal/cli/build.go, pkg/build/oci/oci.go
Fixes #529 
The multi-arch build we added in #499 synchronized `publish` and `build`, and added support for building any arch.
But it did change the `manifest.json` that is output from `apko build`. That PR left the `RepoTags` as just the arch, so your ended up with:
```json
[
{
"Config": "sha256:62e228b24e42fe9a41ffc83ad0c244424844ff5e016d7fc3aef8cba21fb0ea42",
"RepoTags": [
"amd64:latest"
],
"Layers": [
"23b249c599ffedf344a4e6477354208ff76a10ede3ba4237d70c0addb65da953.tar.gz"
]
},
{
"Config": "sha256:849180d1f62d1cee300b9d3958609f7c1dab924927da039c63d08c8691067d50",
"RepoTags": [
"arm64:latest"
],
"Layers": [
"7c214dde647610bc0f9569f45515bba51285ca8b681516908a9bca4cc6d1c626.tar.gz"
]
}
]
```
That obviously was not is desired. This fixes it so that it includes the names of the tags, so …
=> include full tags on images

pkg/apk/apk_implementation.go, pkg/apk/impl/repo.go, pkg/apk/impl/repo_test.go, pkg/apk/impl/version.go, pkg/apk/impl/version_test.go
Fixes #485 
Fixes #540
If `/etc/apk/repositories`, or `repositories` in `apko.yaml`, had pinned repositories, it didn't work:
```
https://foo.org/repos   <-- works
/my/local/dir  <-- works
@pin https://tester.org/repos   <-- FAILS
@local /local/dir   <-- FAILS
```
It wouldn't just ignore it, it would error out.
This PR provides support for:
* reading pinned repositories
* using the pinned repositories for packages
It follows the rules laid out [here](https://wiki.alpinelinux.org/wiki/Alpine_Package_Keeper#Repository_pinning), specifically:
```
You can specify additional "tagged" repositories in /etc/apk/repositories:
Contents of /etc/apk/repositories
http://nl.alpinelinux.org/alpine/v3.7/main
http://nl.alpinelinux.org/alpine/v3.7/community
@edge http://nl.alpinelinux.org/alpine/edge/main …
```
=> add support for pinned repos

pkg/apk/impl/implementation.go, pkg/apk/impl/implementation_test.go, pkg/apk/impl/repo.go, pkg/apk/impl/repo_test.go, pkg/apk/impl/world.go
Small change. apk-tools natively add a newline to `etc/apk/arch` and `etc/apk/world`. It doesn't break anything not to have it or to have it, but it makes it easier to compare built packages, so might as well.
=> add newlines to arch and world

pkg/apk/impl/installed.go, pkg/build/accounts.go
In switching to native, we broke mutate accounts. It was ensuring home directories only for those explicitly added, not those already in `/etc/passwd`. This fixes it by largely bringing it back in sync with the original.
=> fix mutateaccounts

pkg/apk/impl/repo.go
Fixes #549 
When processing a repo named `@local /foo/bar`, we need to take the reference name of the repo (`local`) and the path to it `/foo/bar`. That means a split (don't correctly), and removing the first char (`@`) of the _name_. We accidentally took it off the _path_. Which broke two things.
This fixes it.
=> sliced from wrong part of pinned repo name

.chainguard/source.yaml
The check isn't required, but at least this will give us a nice ✅ instead of the big scary ❌.
=> accept dependabot's GPG key for commit signing CI check

pkg/build/busybox.go
It was missing `/usr/bin/tree`.
=> add tree to busybox

pkg/apk/impl/const.go, pkg/apk/impl/install.go, pkg/apk/impl/installed.go
Fixes #558 
There are two issues.
1. The checksum (in the case of apk, sha1 base64-encoded with a "Q1" header) was not included in the installed file. It now does it. I compared several files to ensure that they are correct and match with apk-tools.
2. It was trying to be too smart in sorting files, which messed up their order, thereby confusing the installation list in the apk installed db. This now is fixed.
While I was at it, I removed unnecessary extra newlines from the installed db. They didn't hurt, but they made it a bit harder to read.
=> Fix installed database

pkg/apk/impl/install.go
We were creating the file in the local file system using just the perms, not the entire mode. This uses the whole mode, causing it to include setuid bits, etc.
@kaniini found this (thank you).
=> get entire mode when opening, not just permission bits

pkg/apk/impl/install.go
We correctly handled the `lib64` directory symlink, but did `continue`, rather than `break`, so we missed adding it back to the list of headers, which are used later to process the apk installed db.
Also added a comment to describe it.
=> handle symlink dir correctly for installed db

pkg/apk/apk.go, pkg/apk/impl/implementation.go, pkg/apk/impl/implementation_test.go, pkg/build/accounts.go
The commits in here fix several permissions mistakes around directories (homedirs, tmp sticky bit, /proc, etc.) They also unify what was in multiple places, and handle errors in perms of existing directories and setting them up better.
=> Permissions fixes

pkg/build/accounts.go
this causes problems with melange, probably due to /home being 0o700 and owned by root
this probably also causes problems with our production images
=> build: accounts: go back to using 0o755 permissions for the homedir

.github/workflows/build.yaml, hack/sbom-quality.sh, internal/cli/build.go, internal/cli/publish.go
Fixes #584 
We were creating a new `BuildContext` for the SBoM generation, rather than reusing the one from the build stage. That meant a new `fsys`, which lost all of the information about the existing one.
This carries it through, enabling us to get all of the information.
This could use a cleaner review, as I am _fairly_ confident I understood the issue in #584 and that this fixes it, but not 100% sure.
=> When build and publish, carry buildcontext to sbom generation

go.mod, go.sum, pkg/apk/impl/implementation.go, pkg/log/log.go, pkg/options/options.go
Instead of using an external log formatter, provide our own formatting policy which is suitable both for apko and melange.  This will be consumed by melange when the logging is converted to logrus.
=> Introduce common logging policy

.golangci.yml, pkg/log/log.go
- for warning and above, color the message text
- the exclamation point emoji is a single-width character, treat it as such
=> log: formatting enhancements

pkg/apk/impl/implementation.go, pkg/apk/impl/index.go, pkg/apk/impl/repo.go, pkg/apk/impl/repo_test.go
This PR does not change the logic of apko. It exposes some of the internal functionality so that it can be used externally as a library.
Specifically:
* `PkgResolver.getPackage()` which would resolve a single package based on constraints now is `ResolvePackage()`
* `NewPkgResolver()` now takes an interface rather than a struct as an argument, so that other structs that implement it can use the resolution functionality.
* `GetRepositoryIndexes()` allows to pass repos and keys and get indexes that can be passed to `NewPkgResolver()`. This was inside a private method of `APKImplementation`, which only functioned on filesystems (`FullFS`). This now lets someone provide the repos and keys and get indexes (that just happen to fulfill the interface for arguments to `NewPkgResolver()`)
=> Abstract apk funcs

internal/cli/publish.go, pkg/apk/apk.go, pkg/apk/apk_test.go, pkg/apk/impl/options.go, pkg/build/build.go, pkg/build/oci/oci.go, pkg/build/options.go, pkg/build/types/image_configuration.go, pkg/exec/exec.go, pkg/exec/exec_test.go, pkg/exec/exec_unit_test.go, pkg/exec/execfakes/fake_executor_implementation.go, pkg/exec/implementation.go, pkg/exec/implementation_test.go, pkg/log/adapter.go, pkg/log/type.go, pkg/options/options.go, pkg/s6/s6.go
Instead of using `logrus` directly, make use of `log.Logger`, and extend it to be suitable for use everywhere.
Add a `log.Adapter` implementation which wraps the logrus-specific details.
=> Use abstract logger type throughout apko core

internal/cli/build-minirootfs.go, internal/cli/build.go, internal/cli/publish.go, pkg/build/oci/oci.go, pkg/build/options.go, pkg/log/adapter.go, pkg/options/options.go
Instead of generating a logger implementation while constructing the build context, accept a pre-existing logger implementation.
=> Provide abstract logger implementation to apko build context

internal/cli/build-minirootfs.go, internal/cli/build.go, internal/cli/publish.go, pkg/iocomb/iocomb.go
A logging policy can be expressed as `--log-policy target1,target2,target3`.
Targets are nominally files on disk, but a few built in targets also exist, such as:
- `builtin:discard`: Discard everything
- `builtin:stdout`: Write to `stdout`
- `builtin:stderr`: Write to `stderr`
For example, `--log-policy builtin:stderr,logs/alpine-edge:latest-20230419.log` will write to both `stderr` and `logs/alpine-edge:latest-20230419.log`.
=> Implement logging policies

pkg/apk/impl/version.go, pkg/apk/impl/version_test.go
If a package requirement is `foo~1.2`, we do not handle it correctly. This now adds support for it. Also adds a few unit tests.
Stage 1 of fixing #627 ; follow-on coming later.
=> add support for tilde matcher

examples/alpine-python3.yaml, pkg/apk/impl/repo.go, pkg/apk/impl/repo_test.go, pkg/apk/impl/version.go
Fixes #627 
Since apk normally does allow self-package resolution (if I fulfill one of my dependencies, then look no further), but other places sometimes do not (e.g. wolfictl, as a policy choice, see [this comment](https://github.com/chainguard-dev/apko/issues/627#issuecomment-1517042175) by @kaniini), we make it optional in the resolver.
We always make it true here, but given the overlap between apko logic and wolfictl graph, and the plans for merging them going forward, making this optional only can help.
=> add optional support for self-package resolution

pkg/apk/impl/repo.go, pkg/apk/impl/repo_test.go, pkg/apk/impl/version_test.go
Fixes #632 
As described in #632, the solver found all packages that either were named with the target (e.g. `a`) and then sorted them. The sorting algorithm, when it came to version order, used the _package_ version. But if the package is there just because it provides something, it should use the _provides_ version.
This fixes it.
=> handle versioning in provides

pkg/build/build.go
Whenever we use apko from a yaml file, the ability to reproduce a failure is easy: the yaml file is right there.
But we use apko as a library from other places, which makes a slower process to tease out how apko was invoked, with what config, and which options, etc.
This causes apko to print out the entire derived config, in the case of failure to `BuildImage()`, only if `--debug` is enabled.
For example:
```
ℹ️  x86_64    | setting apk world
ℹ️  x86_64    | synchronizing with desired apk world
ℹ️  x86_64    | determining desired apk world
❕ x86_64    | buildImage failed: installing apk packages: error getting package dependencies: could not find package, alias or a package that provides wolfi-base2aa in indexes
❕ x86_64    | image configuration:
contents:
repositories:
- …
```
=> report complete yaml when fail to build, if debug is enabled

pkg/build/busybox.go, pkg/build/busybox_test.go
Currently, we maintain a list of all possible links, and generate it using `go:generate`. This has two shortcomings:
* we need to maintain that list by rerunning `go generate` with each new version of busybox
* it includes all possible links (applets), when some may simply not be included in a particular build
With the inclusion of `/etc/busybox-paths.d/<package>` in both alpine (from version 1.36.0-r8 on) and wolfi os (from version 1.36.0-r3 on), we can just parse that file for the links we want.
It will fall back to using the generated files.
Tests for each scenario included.
=> add ability to read busybox links from package manifest

pkg/build/types/types.go
first stab at documenting the fields for apko's public config surface. I best efforted the required/optional fields, knowing that these aren't codegen'd to actually mean anything, but I still think they are useful for an end user.
this will be used by external parsers (like [this](https://github.com/wolfi-dev/wolfictl/pull/193) one) to generate various external documentation that should hopefully improve the devx onboarding/overall experience.
=> document the fields in types/

internal/cli/publish.go, pkg/build/build.go, pkg/build/types/types.go, pkg/build/types/types_test.go, pkg/options/options.go
:broom: This replaces the single-field struct with a simple type alias.
/kind cleanup
=> Cleanup: Use a string alias instead of struct.

pkg/build/image_builder.go, pkg/build/types/types.go
:broom: This cleans up the `map[interface{}]interface{}` currently used for `Services` to match `s6`.
If you look inside of the implementation of the method we pass this to, any path where the key or value aren't strings are errors, so this should be a safe change for any case that is passing today.
/kind cleanup
=> Cleanup: Make the Services type more concrete.

pkg/options/options.go
:bug: Without this we get Go's funky zero value which shows as like `0001-01-01` in our SBOMs.
/kind bug
=> Fix: Explicitly default the `SourceDateEpoch`

.github/workflows/build-samples.yml, .github/workflows/build.yaml
:bug: In a PR with deadlocking we saw things hanging for >60m when thing usually take <10m. This adds generous timeouts much lower than the default of 6h.
/kind bug
=> Fix: add timeouts to several actions legs.

.github/workflows/build-samples.yml, internal/cli/build.go, internal/cli/publish.go, pkg/build/build.go, pkg/build/build_implementation.go, pkg/build/buildfakes/fake_build_implementation.go
:gift: When `SOURCE_DATE_EPOCH` is not specified, this change infers the timestamp to assign the image from the build date of the oldest installed APK.
/kind feature
=> Feature: Compute the default timestamp from installed APKs

internal/cli/build.go, pkg/build/options.go
This PR adds the `annotation` flag to `apko build` for equivalence with `publish`.
It also fixes a bug where the annotations from the yaml config were deleted.
This PR could do with some tests - I'd appreciate any advice on where/how to add these.
=> Fix annotations

pkg/build/os-release.go
Tries to fix #447 
Currently, with my little knowledge of the code being a new contributor here, I could find that mutation of `/etc/os-release` files happens while validation and `ID` tells distro name usually in most `/etc/os-release` files. 
Therefore while checking for `ID`, if it is `""`, we set it to `unknown` in the generated file, this happens in the [Validate function](https://github.com/chainguard-dev/apko/blob/main/pkg/build/types/image_configuration.go#L111). Therefore I added a warning for this there in the check for empty ID. This should probably support what we desired. Thanks!
=> adds warning in case of unknown distro in etc/os-release

pkg/options/options.go
We regularly use `BuildContext.Summarize(logger)` to report the build options, but it only reported 5 of them, missing the rest.
This adds the rest, which should make understand builds (and debugging) easier.
=> extend summarize to provide the rest of the options

go.mod, go.sum
Pulls in `go-apk` with support for pinned repos as dependencies when already installed.
=> go-apk with support for pinned pre-existing as deps

.github/workflows/build-samples.yml, examples/nginx.yaml, pkg/build/oci/index.go, pkg/build/oci/publish.go
This adds any annotations specified in the config file, or determined from VCS info if enabled, to the index manifest in addition to constituent image manifests.
This has always worked, and still does:
```
crane manifest --platform=linux/amd64 $(go run ./ publish examples/nginx.yaml ttl.sh/jason) | jq .annotations
{
"org.opencontainers.image.revision": "d16c9050918e6a5da5bf575d625be7f615b3b966",
"org.opencontainers.image.source": "git+ssh://github.com/chainguard-dev/apko.git"
}
```
This didn't work, but does now:
```
crane manifest $(go run ./ publish examples/nginx.yaml ttl.sh/jason) | jq .annotations
{
"org.opencontainers.image.revision": "d16c9050918e6a5da5bf575d625be7f615b3b966",
"org.opencontainers.image.source": "git+ssh://github.com/chainguard-dev/apko.git"
}
```
(previously the …
=> add annotations to index manifest

pkg/build/oci/image.go, pkg/build/types/types.go
this is to support images that leverage a container runtime that uses the OCI spec `volumes` field ([ref](https://github.com/opencontainers/image-spec/blob/main/config.md#properties)) to set up runtime volume mounts. it is a noop for all other runtimes
this supports the relatively small subset of cases where an image is built to run with `docker`, and needs certain mount configs to function. more concretely, the `k3s` container running in docker (ie: `k3d`). this runs `containerd` in docker by default with the `overlayfs` snapshotter, and requires a non `overlayfs` mount point to work. this is achieved upstream with a host volume mount ([ref](https://github.com/k3s-io/k3s/blob/master/package/Dockerfile#LL16C1-L17C1)).
this change lets us mimic this behavior with something like:
```yaml …
```
=> add optional oci volumes field to resulting image config

examples/wolfi-base.yaml, hack/ci/00-build.sh, hack/ci/01-publish.sh
This changes `make ci` tests to use example configs from `examples/`, instead of a newly invented config
It builds/publishes and runs an alpine-based and a wolfi-based image
This also updates our wolfi-base.yaml example to more closely match the [Chainguard image equivalent](https://github.com/chainguard-images/images/blob/1d3537fa0a782d6a1bf5766a7b6b3741ff5eb221/images/wolfi-base/configs/latest.apko.yaml#L5).
=> base ci tests on examples

go.mod, go.sum, internal/cli/build-minirootfs.go, internal/cli/build.go, internal/cli/publish.go, internal/cli/show-packages.go, pkg/apk/apk.go, pkg/build/build.go, pkg/build/build_implementation.go, pkg/build/oci/index.go, pkg/build/oci/publish.go, pkg/build/oci/sbom.go, pkg/sbom/sbom.go
Also propagate context around a lot of places.
=> Add otel spans

go.mod, go.sum, pkg/build/build_implementation.go
Half of https://github.com/chainguard-dev/apko/issues/779
This cuts our CPU usage in half while cutting latency by ~10ms per layer MB, while producing ~4% larger layers (as compared to pargzip in testing a single image).
Edit: Notably, this will cause some image churn as the layers will compress differently, which will affect digests. We may want to bundle any other content-affecting changes in whatever release contains this.
=> Switch from pargzip to pgzip

pkg/apk/apk.go
Fixes #788 
It should not crash, rather it should report an error.
=> report error when cannot create apkimpl object

internal/cli/build.go, pkg/build/build.go, pkg/build/build_implementation.go, pkg/sbom/sbom.go, pkg/sbom/sbomfakes/fake_sbom_implementation.go
Fixes: https://github.com/chainguard-dev/apko/issues/778
Before:
After:
There is some accidentally quadratic stuff going on there still that we can fix: https://github.com/chainguard-dev/apko/issues/799
=> Don't compute layer hash twice

pkg/build/build.go
We check that the env var `SOURCE_DATE_EPOCH` is _set_ before we try and parse it, but do not account for it being set but blank. We should treat that as unset.
=> when setting SOURCE_DATE_EPOCH, ensure string is not blank

internal/cli/publish_test.go, pkg/build/build_implementation.go
We don't want to accidentally change SBOMs, so this will break if we do.
The wrapper image that cosign generates for SBOMs uses time.Now(), so we have to pull out the layer and test that digest, which is unfortunate, but it's easier than fixing cosign.
=> Add a test to catch SBOM changes

go.mod, go.sum, internal/cli/build-minirootfs.go, internal/cli/build.go, internal/cli/show-packages.go, pkg/apk/apk.go, pkg/build/build.go, pkg/build/build_implementation.go, pkg/build/options.go
I'm not opposed to exposing fields like this in general, but reusing and mutating a build.Context externally has led to me breaking prod, so I'm making these private.
=> Stop exposing build.Context fields

go.mod, go.sum, internal/cli/publish.go, pkg/build/oci/publish.go
This untangles daemon from remote when publishing a bit more, which will make it easier to move towards lazily producing these images, which will make it easier to avoid building things entirely.
=> Split publishing and loading

internal/cli/build.go, internal/cli/commands.go
Fixes #787 
It was ignoring `--workdir`.
=> fix --workdir

internal/cli/publish.go
Given an `apko.yaml` such as the following:
```yaml
contents:
keyring:
- https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
repositories:
- https://packages.wolfi.dev/os
packages:
- ca-certificates-bundle
- wolfi-base
- wolfi-baselayout
- tzdata
- busybox
- build-base
- git
- openssh
- go-1.20
accounts:
groups:
- groupname: nonroot
gid: 65532
users:
- username: nonroot
uid: 65532
gid: 65532
run-as: 0
environment:
GODEBUG: tarinsecurepath=0,zipinsecurepath=0
entrypoint:
command: /usr/bin/go
cmd: help
archs:
- x86_64
- aarch64
annotations:
"org.opencontainers.image.authors": "PlanetScale Infra https://planetscale.com/"
"org.opencontainers.image.url": https://github.com/planetscale/wolfi-images/tree/main/images/go
"org.opencontainers.image.source": …
```
=> fix: incorrect arch tag equality detection

internal/cli/build.go, internal/cli/publish.go, pkg/build/options.go
Build options were only ever used to control appending packages to the list, and multiple options were never used. The functionality was deprecated in https://github.com/chainguard-dev/apko/pull/703 with the introduction of `--package-append` (`extra_packages` in TF-apko)
The PR was merged May 30, released in 0.9 June 30, and build options have been deprecated for two releases now.
=> remove build options

pkg/build/build_implementation.go
pgzip's default is GOMAXPROCS(0)
This is fine for single builds, but we will starve CPU for larger builds. 8 is our max because modern laptops tend to have ~8 performance cores, and large CI machines tend to have ~64 cores.
This gives us near 100% utility on workstations, allows us to do ~8 concurrent builds on giant machines, and uses only 1 core on tiny machines.
=> Set reasonable concurrency levels for pgzip

internal/cli/build.go, pkg/build/build_implementation.go, pkg/build/sbom.go
We need to call a few methods that happen to hang off of build.Context, but they don't actually depend on the dirfs that build.New generates, which is expensive if we've written a large number of files to disk.
This skips that entirely and uses build.NewOptions to get the data we need to generate the index SBOM.
=> Don't call build.New for index SBOM

internal/cli/publish.go
The `--stage-tags FILE` flag is only including the tags explicitly set as positional args to `apko publish`. Any tags generated by `--package-version-tag/stem` are not included.
The `additionalTags` slice is empty when this code is reached. Instead we can use the `allTags` slice generated just before this step instead of shadowing it. `allTags` includes a de-duped set of tags that includes both explicit tags from the command line and any generated/discovered tags that come from package-version and stemming.
=> fix: publish --stage-tags missing generated tags

pkg/build/options.go
When using the `--annotations` flag on a config that does not already/also include an `annotations` YAML key the CLI will panic:
```
panic: assignment to entry in nil map
goroutine 1 [running]:
chainguard.dev/apko/internal/cli.buildCmd.func1.func11(0xc0001a8380)
chainguard.dev/apko/pkg/build/options.go:195 +0xb3
chainguard.dev/apko/pkg/build.NewOptions({0xc000711880, 0x3f}, {0xc00079fca0, 0x10, 0x11f320e?})
chainguard.dev/apko/pkg/build/build.go:186 +0x163
chainguard.dev/apko/internal/cli.buildImageComponents({0x21196d0, 0xc00019a018}, {0xc000711880, 0x3f}, {0x29acab0, 0x0, 0x0}, {0xc00079fca0, 0x10, 0x10})
chainguard.dev/apko/internal/cli/build.go:185 +0x1e8
chainguard.dev/apko/internal/cli.BuildCmd({0x21196d0, 0xc00019a018}, {0x7ff7bfeff6d3, 0x2e}, {0x7ff7bfeff702, 0xf}, {0x29acab0, …
```
=> fix: assignment to nil map when using annotations via CLI flag

internal/cli/build-minirootfs.go, internal/cli/build.go, internal/cli/show-config.go, internal/cli/show-packages.go, pkg/build/build.go, pkg/build/build_implementation.go, pkg/options/options.go
This makes it possible to use a different (forthcoming) FullFS implementation instead of assuming we're writing to a local directory.
This is breaking, but it's a straightforward fix (just construct the dirfs as per the rest of the PR).
Some logs are different, but that's arguably a good thing.
=> Pass a whole fs instead of a workdir to build

internal/cli/publish.go, internal/cli/publish_test.go
fixes #804
quick fix based on the `--sbom-path` logic in the `build` cmd
=> fix: publish cmd --sbom-path not writing files

internal/cli/build.go, internal/cli/publish.go, pkg/build/build.go, pkg/build/options.go, pkg/options/options.go
Using this flag will avoid the network and only use what is available in the cache.
Fixes https://github.com/chainguard-dev/apko/issues/854
=> Plumb --offline flag

internal/cli/build.go, internal/tarfs/fs.go
Actually opt into the optimized tarfs path.
This cuts the amount of time we spend on I/O dramatically.
=> Use tarfs implementation for publish/build

pkg/tarfs/fs.go
I'm a fool and assumed that os.O_RDONLY worked very differently.
=> Don't buffer everything

pkg/tarfs/fs.go, pkg/tarfs/fs_test.go
I got this logic backwards when refactoring this check in go-apk.
=> Allow replacement by different origin

go.mod, go.sum, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/spdx_test.go, pkg/sbom/options/options.go, pkg/sbom/sbom.go, pkg/tarfs/fs.go
This is confusing go's module resolution for some reason. These were recently deleted upstream.
https://gitlab.alpinelinux.org/alpine/go/-/commit/c77a506e8657a0209c6e187f50bdd5af57abb646
=> Drop dependency on deleted packages

go.mod, go.sum, internal/cli/commands.go, internal/cli/dot.go
This is not 100% great because it relies on some pretty naive heuristics to figure out the dependency graph; however, it does produce some pretty useful graphs without touching any existing go-apk or apko code paths, so I think it's a reasonable place to start.
Ideally, we would have ResolveWorld (or something like it) return a graph with metadata about why things resolved the way they did, but that's a more invasive change.
As is, this is great for understanding what packages would get pulled in by apko and what they depend on and/or provide.
=> Add apko dot command

pkg/options/options.go
we were correctly [passing](https://github.com/chainguard-dev/apko/blob/29bca7ce2b8f67909055ee5b9995ae231ee998d7/internal/cli/build.go#L109) and [setting](https://github.com/chainguard-dev/apko/blob/29bca7ce2b8f67909055ee5b9995ae231ee998d7/pkg/build/options.go#L165) any loggers to new builders, but we weren't actually using it because of how `(*Options).Logger()` was being used.
=> ensure propagated logger is used

internal/cli/publish.go
Fixes #817 
Though the command help has a description of which arguments we need.
I have added a custom error msg. (It may not require as the command --help is very clear about the args, suggestions please) 
I am seeing almost all of the command `Usage:` are written in the `Example:` sections.
I have change it for the publish command.
Current help:
=> Improve publish cmd error & usage msg.

pkg/build/oci/image.go
We have concurrent writes to this map. There's probably a nicer way to fix this, but there are a couple of paths through instantiating env, and I don't want to accidentally change any behavior.
=> Clone image config's env to avoid race

.github/workflows/release.yaml, .ko.yaml, Makefile
- remove image building from release process, we recommend cgr.dev/chainguard/apko instead
- don't build Tekton task, nobody uses it AFAIK
- since release.yaml only builds the CLI and only on v-tags, only trigger the workflow on new v-tags
- when building with `ko`, base on `wolfi-base` instead of defunct `alpine-base`
Folks can still use `ko` to build the image locally, but we don't need another apko image to confuse folks/ourselves with.
=> streamline release workflow

pkg/build/types/types.go
Equivalent to https://github.com/chainguard-dev/apko/pull/648, but adds json tags instead of renaming yaml -> json (should ensure consistent behavior for any tools explicitly looking for yaml).
=> Add json tags to ImageConfiguration types.

internal/cli/show-config.go
Looks like we have some missing parenthesis here😅 and never calling the function.
=> Bug Fix: calling the function in `show-config` cmd

pkg/build/types/image_configuration.go
Fix #667
For me the error message was really clear Saying 
```bash
Error: failed to build layer image for "amd64": installing apk packages: error getting package dependencies: error getting repository indexes: repository index not found for architecture x86_64 at https://packages.wolfi.dev/os//x86_64/APKINDEX.tar.gz
2023/10/01 17:40:30 error during command execution: failed to build layer image for "amd64": installing apk packages: error getting package dependencies: error getting repository indexes: repository index not found for architecture x86_64 at https://packages.wolfi.dev/os//x86_64/APKINDEX.tar.gz
```
And yes, This is an easy mistake to make when adding custom package repos.
> This issue did not exist in previous versions of apko (roughly March-April), so is a regression that …
=> Remove Trailing `/` from the repository path

hack/make-devenv.sh
Fixes #605 
Maybe for some recent changes in apko this script was not working.
What I did:
1. in the previous alpine:3.16.0 when we try `apk add go` it is getting the `go-1.19.2` version but in order to run apko we need `go-1.21.*`. As I found it in the edge repository, So I have updated the `BUILDER_ALPINE_TAG`.
2. Currently due to multi-architecture build all the image that we create, the arch name is appended into the image tag. And there is no image with the name `apko-inception:latest`. And for dev-env it is unnecessary to build for all the architecture. 
- Identify the current host architecture. and build only for that.
- Replace the Image name with the proper one.
=> Fixed the `make-devenv.sh` script

NEWS.md
We should cut a release to facilitate a fix for chainguard-dev/melange#501 in downstream providers.
=> Update NEWS.md for 0.11.1

internal/cli/build.go, internal/cli/options.go, internal/cli/publish.go, pkg/build/build.go, pkg/build/build_implementation.go, pkg/build/oci/publish.go, pkg/build/options.go, pkg/build/os-release.go, pkg/build/sbom.go, pkg/options/options.go
In our move toward Terraform-based image builds, we no longer use a number of flags we had previously used -- mainly around tagging.
This PR drops some flags we don't use anymore, in an attempt to delay the implacable advance of entropy that lies at the heart of the human experience.
- `--stage-tags` used to skip tagging -- now we just invoke the build and tag later with [`oci_tag`](https://registry.terraform.io/providers/chainguard-dev/oci/latest/docs/resources/tag)
- `--use-docker-mediatypes` used to use Docker-style media types -- now we just always publish OCI images
- `--package-version-tag`, `--package-version-tag-stem`, `--package-version-tag-prefix`, `--tag-suffix` all used to control version-tagging logic in apko; now we do this version string extraction and tagging in …
=> cleanup: remove unused flags

.github/workflows/build-samples.yml, .github/workflows/build.yaml, go.mod, go.sum, internal/cli/dot.go, internal/cli/resolve.go, internal/cli/show-packages.go, pkg/build/build_implementation.go, pkg/build/busybox_test.go, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/spdx_test.go, pkg/sbom/options/options.go, pkg/sbom/sbom.go, pkg/tarfs/fs.go
Pick up https://github.com/chainguard-dev/go-apk/pull/150
=> use forked alpine-go in go-apk

go.mod, go.sum, pkg/build/busybox_test.go, pkg/tarfs/fs.go, pkg/tarfs/fs_test.go
We were ignoring multiple Replaces when installing files, which broke any packages that relied on replacing multiple packages. This fixes things for those packages, but also fixes the installed db file to include the replaces line that was missing.
=> Fix packages with multiple Replaces

internal/cli/lock.go
Make sure list of 'repositories' in the 'resolved.json.file' is complete.
Prior to this PR, there were only listed used repositories used by any of the artifacts for given arch.
On the other hand the list was used to run APKO in offline environment -> and missing repos were leading to a failure
(in rules_apko).
Eventually repositories and indexes will not be needed for creation of image from resolved file, but, if we have the list in the file-format -> it should be complete.
=> Make sure list of 'repositories' in the 'resolved.json.file' is complete.

internal/cli/publish_test.go, internal/cli/testdata/golden/sboms/sbom-aarch64.spdx.json, internal/cli/testdata/golden/sboms/sbom-x86_64.spdx.json, pkg/build/sbom.go, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/spdx_test.go, pkg/sbom/options/options.go
Note that the golden SBOMs were updated to drop the duplicate etc/os-release entries.
=> Use idb to drive sbom file inclusion

pkg/sbom/generator/spdx/spdx.go
I didn't catch this in testing because newer versions of melange don't emit filenames with the leading slash, and I used a newer version of melange to generate the testdata.
Everything seemed to work except for APKs that haven't been rebuilt since melange was updated.
=> Strip leading slash before sbom ownership check

go.mod, go.sum, pkg/build/build.go
This should be functionally equivalent but drops the multierror dependency.
=> Drop multierror for errgroup

pkg/build/types/image_configuration.go
Fixes #1001
```
$ apko build /does/not/exist  example.com:latest ./out
ℹ️            | loading config file: /does/not/exist
⚠️            | loading config file failed: open /does/not/exist: no such file or directory
⚠️            | attempting to load remote configuration
⚠️            | NOTE: remote configurations are an experimental feature and subject to change.
⚠️            | loading remote configuration failed: unable to fetch remote include from git: failed to clone /does/not/exist: Get "https://does/not/info/refs?service=git-upload-pack": dial tcp: lookup does: no such host
Error: failed to load image configuration: open /does/not/exist: no such file or directory
2024/01/05 14:38:51 error during command execution: failed to load image configuration: open /does/not/exist: no such …
```
=> Return better error messages for missing config

main.go
This gives apko a chance to clean up after itself.
=> Cancel context on interrupt signal

internal/cli/dot.go
Listen() is hanging so we never exit.
=> Allow apko dot to be cancelled

internal/cli/lock.go, internal/cli/testdata/apko.lock.json, pkg/build/build_implementation.go, pkg/build/options.go, pkg/build/types/image_configuration.go, pkg/lock/lock.go, pkg/options/options.go
Without this, it was easy to forgot updating lock-files, so got images based on the stale lock-file.
Now, if the `apko.yaml` (or one of the included files) is changed without refreshing the `apko.lock.json` file, the 
apko build will fail. 
The behavior is backward compatible, i.e. it triggers only when the new lock-files (with `config { deepChecksum: ...}} fields`) are used.
=> Store checksum of apko-config in the lock-file to detect changes in origin.

hack/ci/01-publish.sh, internal/cli/publish_test.go, internal/cli/testdata/golden/sboms/sbom-aarch64.spdx.json, internal/cli/testdata/golden/sboms/sbom-x86_64.spdx.json, pkg/sbom/generator/spdx/spdx.go
Including files in the SBOMs makes them _huge_ with no discernible benefit.
We removed files from package SBOMs in https://github.com/chainguard-dev/melange/pull/1076 but this means we don't have to rebuild every package to get sanely-sized SBOMs out of apko.
=> ignore Files when generating SBOMs

docs/apko_file.md, pkg/build/accounts.go, pkg/build/types/schema.json, pkg/build/types/types.go
Allows passing a different value for the configured user's shell. Defaults to /bin/sh.
=> feat(user): Allow overriding the default shell

internal/cli/publish_test.go, internal/cli/testdata/base_image/sboms/sbom-aarch64.spdx.json, internal/cli/testdata/base_image/sboms/sbom-x86_64.spdx.json, internal/cli/testdata/golden/sboms/sbom-aarch64.spdx.json, internal/cli/testdata/golden/sboms/sbom-x86_64.spdx.json, pkg/sbom/generator/spdx/spdx.go
https://github.com/chainguard-dev/apko/pull/1073 removed `files` from SBOMs, but didn't remove enough.
It turns out, if `references` mention an `SPDXRef-File--` then that object must also exist in the graph, and we removed those.
This change further expunges files information from references, so that SBOMs are SPDX-valid.
=> spdx: remove more mentions of files

internal/cli/publish_test.go, internal/cli/testdata/base_image/sboms/sbom-index.spdx.json, internal/cli/testdata/golden/sboms/sbom-index.spdx.json, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/sbom.go
Index SBOMs had been defaulting to reporting as supplied by `Alpine Linux` due to a long-standing bad default.
This removes the default, and index SBOMs now report `supplier: NOASSERTION` instead of erroneously stating Alpine.
=> fix: remove default supplier for index SBOMs

pkg/build/types/image_configuration.go, pkg/build/types/image_configuration_test.go, pkg/build/types/testdata/overlay/base.apko.yaml, pkg/build/types/testdata/overlay/overlay.apko.yaml, pkg/build/types/testdata/overlay/overlay_with_package.apko.yaml
The problem was with
```
copier.CopyWithOption(&mergedIc, ic, copier.Option{IgnoreEmpty: true})
```
If `Contents` object of overlay config was empty, then the merged config kept the repeated fields of contents from base config. Then the merging of repeated fields was done as concatenating base arrays with merged arrays, effectively doubling each array from base.
=> Fix duplicates when overlaying the config with config with no contents

pkg/sbom/generator/spdx/spdx.go
If licenserefs are passed, include them in the SPDX document.
Related: https://github.com/chainguard-dev/melange/issues/1212
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@chainguard.dev>
=> spdx: allow specifying custom license

pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/spdx_test.go, pkg/sbom/generator/spdx/testdata/expected.spdx.json, pkg/sbom/generator/spdx/testdata/font-ubuntu.spdx.json, pkg/sbom/generator/spdx/testdata/generate.sh
This fixes https://github.com/chainguard-dev/apko/pull/1127
With package SBOMs now containing custom license information (i.e. font-ubuntu), teach Image SBOM generator to merge those.
Error out if two packages use the same licence-ref but with different extracted license text, as that would be an invalid SBOM merge. This feels nicer than force renaming licenseIDs with multiple duplicate
texts.
Tested by generating apko image with just font-ubuntu package, and verifying that with this change, the image sbom now passes checkers.
This should fix:
> Unrecognized license reference: LicenseRef-ubuntu-font. license_expression must only use IDs from the license list or extracted licensing info, but is: LicenseRef-ubuntu-font
Error from the docker-selenium spdx json
=> sbom: fixup merging LicensingInfos during Image SBOM generation

internal/cli/build.go, internal/cli/publish.go, pkg/build/build.go
As written we refuse to pass auth unless the `HTTP_AUTH` variable DOES NOT have 4 parts, but we really want the opposite.
This change makes things more strict and we will actually error out if `HTTP_AUTH` is specified but malformed.
=> This fixes the boolean logic to pass auth.

pkg/build/accounts.go
follow on to #1146, which introduced the necessary plumbing from the `ImageConfiguration` side of things, but didn't ensure the non-default option wasn't overridden by the `userToUserEntry()`.
=> ensure homedir respects non-defaults

go.mod, go.sum, internal/cli/build.go, internal/cli/publish.go, pkg/build/build.go, pkg/build/build_test.go, pkg/build/options.go, pkg/options/options.go
Builds on https://github.com/chainguard-dev/go-apk/pull/281
This augments `HTTP_AUTH` handling to (ab)use the `realm` component to specify the domain that the auth should be used for. Domains that don't have auth specified don't pass a user+pass; those that do, do.
=> enable per-host auth

examples/old-glibc.yaml, pkg/sbom/generator/spdx/spdx.go
We've had some issues where apko can't build images from old packages that contain files data in the package SBOMs, resulting in errors like:
```
│ generating sbom for amd64: generating spdx sbom: parsing internal apk SBOM: copying element: unable to find 137 elements in source document: [SPDXRef-File-/usr/bin/objdump
│ SPDXRef-File-/usr/bin/size SPDXRef-File-/usr/lib/libctf.la SPDXRef-File-/usr/x86_64-pc-linux-gnu/bin/readelf SPDXRef-File-/usr/x86_64-pc-linux-gnu/lib/ldscripts/elf_iamcu.xce
│ SPDXRef-File-/usr/x86_64-pc-linux-gnu/lib/ldscripts/elf_x86_64.xswe SPDXRef-File-/usr/bin/gprof SPDXRef-File-/usr/lib/bfd-plugins/libdep.so SPDXRef-File-/usr/share/man/man1/addr2line.1
│ SPDXRef-File-/usr/x86_64-pc-linux-gnu/lib/ldscripts/elf_iamcu.xsw SPDXRef-File-/usr/share/man/man1/strip.1 …
```
=> add test that images with old packages can build

pkg/apk/apk/package.go, pkg/apk/apk/package_test.go, pkg/apk/expandapk/split.go, pkg/apk/expandapk/split_test.go, pkg/apk/expandapk/testdata
We have a lot of code that calls ExpandAPK. It's a convenient function, but it's incredibly expensive because it does everything all at once. This wasn't supposed to be exposed, but it escaped the lab.
What's worse is that we have things like ParsePackage being used all over the place that also call ExpandAPK. Most things calling ParsePackage only care about the .PKGINFO file, but we end up caching tons of stuff to disk and hashing every file in the APK. This is very wasteful.
Instead, this adds a new expandapk.Split function that just returns a slice of readers in the order they're encountered. The first 1 (or 2 if signed) readers are just buffered bytes. The last reader is whatever remains from the input, which will be the data section.
This allows us to rewrite ParsePackage to be much …
=> Add expandapk.Split and use it

internal/cli/publish.go
Fixes #1057.
Mirror `--lockfile` arg from `build` to `publish`.
(See also #1069, which seems to have gotten stuck on contribution guidelines)
=> fix: Add lockfile option to publish command

internal/cli/build-minirootfs.go, internal/cli/build.go, internal/cli/build_test.go, internal/cli/dot.go, internal/cli/lock.go, internal/cli/lock_test.go, internal/cli/publish.go, internal/cli/publish_test.go, internal/cli/show-config.go, internal/cli/show-packages.go, internal/cli/testdata/apko.lock.json, pkg/build/build.go, pkg/build/build_test.go, pkg/build/options.go, pkg/build/types/image_configuration.go, pkg/build/types/image_configuration_test.go, pkg/options/options.go, pkg/paths/paths.go, pkg/tarfs/fs_test.go
This works in similar fashion as PATH variable. All config files are searched for in provided include-paths.
By config files I mean:
1. The config file itself
2. Included configs
3. Base image and it's metadata
=> Add include-paths flag to build and lock.

internal/cli/build.go, internal/cli/dot.go, internal/cli/lock.go, internal/cli/publish.go, internal/cli/show-config.go, internal/cli/show-packages.go, internal/cli/testdata/apko.lock.json, internal/cli/testdata/image_on_top.apko.lock.json, pkg/apk/apk/repo.go, pkg/build/apk.go, pkg/build/build_test.go, pkg/build/options.go, pkg/build/types/image_configuration.go, pkg/build/types/image_configuration_test.go, pkg/build/types/schema.json, pkg/build/types/testdata/overlay/base.apko.yaml, pkg/build/types/testdata/overlay/overlay_with_package.apko.yaml, pkg/build/types/types.go, pkg/lock/lock.go, pkg/options/options.go
There are three interesting use cases enabled by this change:
1. Silence `./packages` warnings with our private images.
Currently for our private images, we pull private packages via GCS fuse mounted to `./packages/`.  This results in warnings from `apk` when the indices are updated today because this path does not exist.
By making `./packages` a build-time only thing, this goes away.
2. Stop leaking auth in build repository URLs into the final image
Currently it is impossible to use `https://user:pass@repo` style repositories without the credential leaking into the image's `/etc/apk/repositories`.
With this change, credentialed URLs may be passed to `--build-repository-append` and the credentials will only be used for the initial image construction and not be present in the final image. …
=> Plumb through the notion of build-time repositories.

internal/cli/build.go, pkg/apk/apk/implementation.go, pkg/apk/apk/repo.go, pkg/apk/apk/repo_test.go, pkg/build/multi.go, pkg/tarfs/fs_test.go
When building an image with multiple architectures, we now disqualify any packages that aren't available on every architecture.
An example given wolfi trying to solve for `trivy=0.36.1-r2`, which was only built for arm64, probably because there was a bug in the build that was fixed in a subsequent epoch:
>   for arch "arm64": installing apk packages: error getting package dependencies: solving "trivy=0.36.1-r2" constraint:
>   ...
>   trivy-0.36.1-r2.apk disqualified because package "trivy-0.36.1-r2.apk" not available for arch "amd64"
=>  Make solving multi-architecture aware

go.mod, internal/cli/build.go, internal/cli/publish.go, pkg/apk/apk/implementation.go, pkg/apk/apk/implementation_test.go, pkg/apk/apk/index.go, pkg/apk/apk/options.go, pkg/apk/apk/repo.go, pkg/apk/apk/repo_test.go, pkg/apk/auth/auth.go, pkg/build/build.go, pkg/build/build_test.go, pkg/build/options.go, pkg/options/options.go
Opening as draft to discuss.
This refactors our current auth handling -- reading `HTTP_AUTH` env var once at CLI startup, and passing through build options -- with a more cred-helper-centric form, with `EnvAuth` mimicking the current behavior, and `CGRAuth` providing an implementation that relies on `chainctl auth token`.
Go API consumers can choose to implement other auth helpers if they want, or change the behavior of the default if they want.
This should be backward-compatible with apko CLI, but breaks the Go API in ways that Melange and TF-Apko will have to adapt to.
=> auth: refactor into Authenticator interface

internal/cli/lock.go, internal/cli/testdata/apko.lock.json, internal/cli/testdata/image_on_top.apko.lock.json, pkg/apk/apk/resolveapk.go, pkg/apk/apk/util.go
The previous logic didn't properly handle unsigned APKs.
=> Simplify the resolution logic to use `expandapk.Split`

.github/workflows/build-samples.yml, hack/ci/00-build.sh, hack/ci/01-publish.sh
Openssl on [riscv64]( https://apk.dag.dev/https/dl-cdn.alpinelinux.org/alpine/edge/main/riscv64/APKINDEX.tar.gz@etag:36363835623333652d3731343934/APKINDEX?full=false&search=openssl-3&depend=&provide=) returns [openssl-3.3.1-r1.apk](https://apk.dag.dev/https/dl-cdn.alpinelinux.org/alpine/edge/main/riscv64/openssl-3.3.1-r1.apk@sha1:723b9ab5dca1151f3d9dffa2e143c2482eef2e7c)
where are on [aarch64](https://apk.dag.dev/https/dl-cdn.alpinelinux.org/alpine/edge/main/aarch64/APKINDEX.tar.gz@etag:36363837373638322d3733373166/APKINDEX?full=false&search=openssl-3&depend=&provide=) returns [openssl-3.3.1-r2.apk](https://apk.dag.dev/https/dl-cdn.alpinelinux.org/alpine/edge/main/aarch64/openssl-3.3.1-r2.apk@sha1:5ce776fb7e56089507d7c30b654ed332341204d5)
Causing CI tests and other tests to fail on the …
=> openssl on alpine(Riscv64) returns a different version causing ci failures 

pkg/apk/apk/index.go
wolfing text was failing because of nil pointer 
```
2024/07/04 23:19:55 INFO   adding package "scanelf" for pipeline "Strip binaries"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x102841114]
goroutine 1 [running]:
chainguard.dev/apko/pkg/apk/apk.getRepositoryIndex({0x105a6d938, 0x1400a061230}, {0x1400af57300, 0x34}, 0x1400345b848, {0x1046100b3, 0x6}, 0x1400937e4c0)
chainguard.dev/apko@v0.16.0/pkg/apk/apk/index.go:212 +0x2f4
chainguard.dev/apko/pkg/apk/apk.(*indexCache).get.func1()
chainguard.dev/apko@v0.16.0/pkg/apk/apk/index.go:72 +0x50
sync.(*Once).doSlow(0x1074fc560?, 0x1054607e0?)
sync/once.go:74 +0x100
sync.(*Once).Do(...)
```
After fix
```
2024/07/04 23:24:02 INFO   adding package "git" for …
```
=> index throws nil pointer when no auth set

pkg/apk/apk/cache.go, pkg/apk/apk/index.go, pkg/apk/apk/repo.go, pkg/apk/apk/version.go, pkg/apk/apk/version_test.go, pkg/build/apk.go
I've been taking a look at where we're spending time on some mega-builds and on my machine it takes ~250ms to call NewPkgResolver for each image.
This is fast in the grand scheme of things but not if we need to do it thousands of times. The main culprit here is a regex, which sucks, but we hacked around that by caching the results in a map. This takes that one step further and introduces yet another (I know, sorry) global cache of the things that need a regex. This is less terrible than the other instances, IMO, because the cached functions are pure and take only version strings as inputs.
Using a sync.Map over a map doesn't seem to be measureably slower on my machine in the worst case (the first time we call NewPkgResolver), and subsequent calls drop from ~250ms to ~90ms.
We can still do …
=> Faster NewPkgResolver and GetRepositoryIndexes

go.mod, pkg/apk/apk/implementation.go, pkg/apk/apk/implementation_test.go, pkg/build/apk.go
The protocol follows a roughly similar handshake to OIDC discovery, hitting `{repository}/apk-configuration`, extracting the `jwks_uri` and then recording each pem-encoded key as `/etc/apk/keys/{kid}.rsa.pub`.
I have tested this locally with both public and private APK repositories against `apk.mattmoor.dev` with the changes in: https://github.com/chainguard-dev/mono/pull/18431
Once this lands, I can use this in e2e tests there, but those are somewhat 🐔  & 🥚
=> Implement client-side APK discovery in `apko`

pkg/apk/apk/client.go, pkg/apk/client/client.go
The idea here is to orient remote APK interactions around a **client**, in order to give consumers the ability to handle dependency injection properly (such as by injecting an HTTP client).
And the ultimate goal is to re-use this client whenever we need to access remote indexes and packages. It'd be great if we can refine this API enough where we can reuse this in all the places we need to interact with APK repositories, to replace the many disparate implementations of this logic we have in our tools today.
I haven't gone as far as to refactor other code in apko to use this client, but I think that's a reasonable next step. So far this implementation saves me from writing it again in an internal tool.
Feedback welcome. 😃 
cc: @imjasonh
=> begin a new APK client

go.mod, go.sum, internal/cli/build-cpio.go, internal/cli/commands.go, pkg/cpio/layer.go
This makes it significantly simpler to produce `.cpio` files from an apko file.
Marking the command as hidden for now, since this is still somewhat experimental.
=> Create a command similar to `build-minirootfs` for CPIO

pkg/build/lock.go, pkg/build/lock_test.go
This pulls the configuration locking functionality out of tf-apko and creates a function in `apko` to hold this.
=> Migrate the configuration locking to `apko`.

pkg/build/types/types.go, pkg/build/types/types_test.go
I noticed downstream that if I used `x86_64` in an apko yaml that the resulting OCI platform would be `x86_64` instead of `amd64`.
With this change, we always canonicalize the architecture before each switch statement to ensure that we are dealing with a canonical form of the architecture.
This adds a regression test for the OCI cases specifically.
=> Canonicalize the architecture.

go.mod, go.sum, pkg/apk/apk/cache.go, pkg/apk/apk/implementation.go, pkg/apk/apk/index.go
This was only imported to enable handling file paths as URLs, which we can do by just adding `file://`.
=> drop dependency on go.lsp.dev/uri

pkg/apk/auth/auth.go, pkg/apk/auth/chainguard.go
With this change, by default:
1. if `HTTP_AUTH` is set and parseable, we'll try to use that token for apk auth.
1. if `CHAINGUARD_IDENTITY` and `K8S_TOKEN_PATH` are set, we'll try to use a K8s SA token and exchange it for the CG identity.
2. if `CHAINGUARD_IDENTITY` is set and (1) didn't set auth, we'll try to get a GCP token and exchange it for a CG identity token.
3. finally, if none of the above has worked, and `chainctl` is available, we'll try to get a token from that.
For K8s auth: in order for the exchange to work, the token must be projected into the path, with a matching configured audience, and the identity has to be assumable by the token (its issuer, subject and optionally its claims)
=> auth: attempt CG auth if envs are configured

pkg/build/types/schema.json, pkg/build/types/types.go
LoongArch is a newish ISA that was introduced by Loongson, who previously made MIPS64r2 processors.
LoongArch is essentially a fork of MIPS64r5 with some RISC-V influences added alongside Loongson's previous proprietary MIPS extensions.
The apk architecture name for this architecture is 'loongarch64', while the OCI architecture name is 'loong64'.
This change allows apko to build images for the Alpine loongarch64 port.
=> Add LoongArch architecture definition

pkg/apk/fs/memfs.go, pkg/apk/tarball/write.go, pkg/tarfs/fs.go
We were overwriting all the file timestamps with a configurable SOURCE_DATE_EPOCH, which was always the unix epoch. The only reason we were doing this is that we were also setting the modtime of everything to time.Now() elsewhere.
That's silly.
Instead, don't set anything to time.Now() and keep file modtimes when we add them to the filesystem. If the APKs change, nothing will be reproducible anyway, so keeping the data from the APK seems way better.
=> Keep apk modtime

pkg/apk/tarball/tarball.go, pkg/apk/tarball/write.go
We don't use this (and we don't want it) but melange uses the tarball package, so let's avoid breaking that for now until we can migrate stuff off of this tangled web of weird fs.FS implementations.
=> Restore SourceDateEpoch in tarball for melange

pkg/apk/auth/chainguard.go
Without this, it's only called once and creds are never refreshed
=> cg auth: fix sometimes

pkg/apk/apk/apkindex.go
We expect some blank lines, which delimit each entry. We expect every other line to have at least e.g. "C:", i.e. a single character followed by a colon.
I looked at our current APKINDEX to make sure I'm not missing anything:
```
$ awk '{print length}' APKINDEX | sort -n | uniq -c | head
83376 0
11137 2
7807 3
1214 4
18924 5
23738 6
49958 7
126520 8
62586 9
86165 10
```
We don't have any single-character lines, so this change should be fine.
=> Fail if APKINDEX has single-character lines

.goreleaser.yaml
Closes #1276 
Closes #639 
By using pre-releases, new updates are not discoverable by users and tooling.  GitHub does not promote these as much, and tools like Renovate and Dependabot will exclude all pre-release packages by default.
This PR changes the Goreleaser configuration to no longer create pre-release packages, and instead create proper releases which will be available at the https://github.com/chainguard-dev/apko/releases/latest URL.
While I do not know anything about goreleaser, there is a `prerelease: true` line which does look to be the cause for this.
This appears to have been set when GoReleaser was [first introduced to this repository over two years ago](https://github.com/chainguard-dev/apko/commit/50a81ccf1e901ea54eb5326aa63a0f1a90aa0405), and I assume may have been …
=> fix(ci): mark GitHub releases as latest from prerelease

internal/cli/dot.go
The help for every other command does not end with a period so let's make them consistent.
=> Drop a period from a command's help

internal/cli/build.go, internal/cli/dot.go, internal/cli/publish.go, internal/cli/show-config.go, internal/cli/show-packages.go, pkg/apk/apk/cache.go, pkg/apk/apk/implementation_test.go, pkg/apk/apk/index.go, pkg/apk/apk/options.go, pkg/apk/apk/repo_test.go, pkg/build/build.go, pkg/build/build_test.go, pkg/build/options.go, pkg/options/options.go
This isn't perfect but I think it moves us closer in the right direction. Previously, we had a process-wide global etag cache that would prevent sending multiple HEAD requests to check the etag value of any URLs we fetched (keys and APKINDEX, mostly).
This is great for a local tool or even the terraform provider, but it's awful as a library used by a service because the lifetime of the process is liable to outlive the validity of the cach.
This hoists that global etag caching mechanism out into a little apk.Cache struct, which is where I'm hoping to put even more things that I'm ashamed of going forward.
Using the same apk.NewCache(true) instance across multiple builds will skip HEAD requests to the same URL and just assume that the tag hasn't changed. This was the previous default …
=> Make etag checks optional

pkg/apk/apk/install.go, pkg/apk/fs/fs.go, pkg/apk/fs/memfs.go, pkg/apk/fs/rwosfs.go, pkg/build/build_implementation.go, pkg/tarfs/fs.go
This worked in our happy tarfs path but not in the dirfs path that melange uses because some runners mount directories rather than actually packaging the layer up into an image. This made it impossible to test the timestamps properly in package tests because the APK files had modtimes set to SOURCE_DATE_EPOCH.
=> Preserve APK timestamps when using dirfs

pkg/apk/apk/cache.go, pkg/apk/apk/index.go
I thought it was clever to use If-None-Match because it was pretty close to what I wanted, but the way we're wrapping transports means that this actually breaks if the Etag matches. Whoops!
Just change this to an invalid header so that this stops breaking, we can fix it better later by making the cache not look like a transport.
=> Stop using real headers for side channels

pkg/build/oci/image.go
This is a quick fix to a race condition we're hitting when building multi-arch images. The ImageConfiguration struct gets passed around by value, but the collections (e.g. annotations) don't get copied, so if multiple architectures attempt to set an annotation at the same time, we'll hit a race. This creates a defensive copy to avoid that.
=> Avoid race when mutating annotations

pkg/sbom/generator/spdx/spdx.go
not specifying the `downloadLocation` is invalid according to SPDX.
Instead of setting it to `pkg.URL` which might be empty, set it to `NOASSERTION`.
=> set downloadLocation to NOASSERTION when apk.URL is unset

pkg/build/types/image_configuration.go
Just appending to maps or slices is not great in a concurrent universe, so my previous fix was in fact not fixing much of anything, whoops.
=> Make MergeInto threadsafe

pkg/apk/signature/rsa.go
Now that known users of these APIs have migrated to functions calls
with an explicit hash, remove these backward compat APIs.
This will catch any unknown users of these APIs.
=> rsa: remove backwards compat APIs

pkg/apk/auth/auth.go, pkg/apk/auth/auth_test.go
Previously we would fail if any authenticator returned an error. With this change, each authenticator is attempted and if any return an error the errors are aggregated and only returned if no token is successfully set.
=> Allow multiauthenticator to try all authenticators

pkg/apk/apk/implementation.go
On cache miss, we'll expand and APK into a tempdir, then move all the files into the final place in our cache dir. On ExpandedAPK.Close(), we'll remove that tempdir.
If we have concurrent images installing the same package, one might clean up the tempdir while the other still has a reference to the tarball sitting in the tempdir, so subsequent reads fail.
Instead, we need to re-instantiate the tarfs after we move it to the cache dir. This could be much more efficient (we re-scan the tar). I'm working on that in a separate branch, so left a TODO for now.
=> Re-instantiate each APK's tarfs after caching

pkg/apk/apk/implementation.go
I'm using a gcsfuse mounted bucket as a cache and seeing some unexpected behavior when trying to read a file immediately after renaming it. I'm not sure if this will help or not but I want to try it.
=> Attempt to flush renamed files in cache

pkg/apk/apk/cache.go
Currently there is a bug in `cacheTransport` I found when working on #1378 where non-success status codes do not result in a returned `error` (despite exiting early) resulting in other confusing/hard to debug problems later on.
=> fix: ensure cacheTransport returns an error for non-200 responses

pkg/apk/apk/options.go
Resolves #1378 where `--cache-dir` was broken after in 0.19.3+ due to a regression in #1327. This error happened because `cacheDir` is not an absolute path when provided via the CLI option. This PR fixes the bug by resolving `cacheDir` to an absolute path when initializing the `cache` instance.
=> fix: --cache-dir broken after in 0.19.3+

internal/cli/build-cpio.go
These are copied directly from `build`
=> Add support for extras in `build-cpio`

pkg/build/accounts.go, pkg/build/types/image_configuration.go
Currently, we block new users from belonging to GID 0. While this is a great practice, some images may expect that the configured user belong to GID 0 so remove the limitation
=> fix: Allow accounts to belong to GID 0

pkg/sbom/generator/spdx/spdx.go
To point out why multiple extracted license texts might differ when the image is built.
cc: @wojciechka
=> fix(spdx): more helpful error message on license merge

pkg/apk/apk/installed.go, pkg/apk/apk/installed_test.go
This should probably be an allowlist like apk does, but this is a smaller diff and I'm worried about breaking more things.
=> Ignore scripts that aren't executable

pkg/apk/signature/sign.go
Remove commented out support for dual-signing, as it is not correctly
supported by anything (non-deterministic validation, leading to
trusting weakest signature, rather than strongest one).
Switch default signing type to RSA256 (RSA signature over SHA2-256
message digest).
Provide environment variable opt-out to switch back to RSA (RSA
signature over SHA1 message digest).
This allows to roll this out, with a runtime escape hatch.
If successful, runtime escape hatch can be reverted.
All tests pass, as support for validating RSA/RSA256/dual signatures
was already landed previously.
This api is used by melange and has been cross-tested with melange (using replace go.mod directive pointing at this proposed apko code).
=> pkg/apk: switch to SHA2-256 based signatures by default

pkg/build/lock.go
This eliminates a subtle source of locked config diffs depending on whether we sort with or without the version string present.
=> Add an explicit sort to squash diffs.

pkg/build/accounts.go, pkg/build/accounts_test.go, pkg/build/types/image_configuration_test.go, pkg/build/types/types.go, pkg/build/types/types_test.go
A follow up to https://github.com/chainguard-dev/apko/pull/1407 which had the unintended side effect of missing gid value defaulting to 0
=> Make GID its own type to prevent defaulting to 0

pkg/build/types/types.go
This introduces an apko:experimental struct tag so that we can ignore it in our reflection-based terraform schema generation in terraform-provider-apko.
This wasn't a problem before because we ignored pointers, but when we moved GID to a *uint32, we started ignoring it in our terraform provider. Fixing that (by dereferencing pointers in the reflection code) had an unfortunate effect of bringing the base image stuff into the generated schema, which I don't want to do yet because it's experimental. Adding this tag lets me filter it out without hardcoding specific field names (ew).
=> Mark base image as experimental

pkg/build/types/image_configuration.go, pkg/build/types/image_configuration_test.go, pkg/build/types/testdata/users.apko.yaml
Follow up to comment here: https://github.com/chainguard-dev/apko/pull/1449#issuecomment-2568110052
cc @pnasrat
=> Fix logging output of user.GID

internal/cli/build-minirootfs.go
I didn't realize I'd only added these to `build-cpio`, but this copies them over.
=> Add the extra flags to `build-minirootfs`

pkg/apk/apk/cache.go, pkg/apk/apk/repo_test.go
These values need to be safe as filenames for --offline to work consistently.
=> Base32-encode etag values

pkg/apk/apk/repo.go
We were missing a couple of edges that would help make it clearer why we were solving a constraint.
In particular, this DepError was problematic:
https://github.com/chainguard-dev/apko/blob/995ee5a40608591b2c4d2e7893abdffeca93f6ff/pkg/apk/apk/repo.go#L798
We were returning an error for the outer "pkg" and not including the context of the constraint within that package being solved or the failure of the selected package to solve its deps.
=> Improve error graph for failed solve

pkg/build/lock.go
Fix #1471
Dear @jonjohnsonjr,
Can you please review my change? I noticed your PR [here](https://github.com/chainguard-dev/apko/pull/1468). I was also looking in the issue and this change worked.
=> Fix package name handling to retain version and strip ‘@’ suffix

pkg/apk/apk/index.go
This reverts commit 8f52674badbb93625e09bca17d4922e5308c707d.
=> Revert "Disallow `/` in key names"

pkg/apk/apk/index.go
We weren't actually checking the response code, so we get weird gzip errors instead of the HTTP status.
=> Return an if fetching index fails

.gitignore, internal/cli/build.go, pkg/apk/apk/implementation.go, pkg/apk/apk/repo.go, pkg/build/oci/publish.go, pkg/build/options.go, pkg/build/types/image_configuration.go, pkg/build/types/schema.json, pkg/build/types/types.go
- don't log requests to `apk-configuration`
- don't log what architectures we're building for by default
- don't log what apk repositories we're using by default
- don't log "skipping local tagging" which isn't warn-worthy or even debug-worthy (we always do this)
- deprecate some stuff we don't use and shouldn't recommend
=> move some unnecessary logs to debug

examples/abseil-regression.yaml, pkg/apk/apk/repo.go, pkg/apk/apk/repo_test.go
We ran into a very very slow solve. I can't tell if it was actually slow
or infinite, but it didn't seem to be convering very quickly. I realized
that we essentially recurse the entire graph for every constraint, even
for things we've already solved. This was surprising, because I thought
we handled that already, but it seems like we didn't.
I've added an example "abseil-regression.yaml" that took over a second
to solve (as of this writing) before this change and takes about 1ms
after this change. There's an open PR in wolfi that timed out because
the abseil dep graph got even more gnarly and took several hours, so
there was something (at least) quadratic going on here, oops.
I've deleted a test that was exercising a scenario where packages were
disallowed from providing themselves …
=> Consider already selected packages during solve

pkg/sbom/generator/spdx/spdx.go
Explain that SHA1 usage in SPDX is forced upon us from APKINDEX & git,
rather than by-choice. As the checksums documented here, are those
that can be externally and independently verified.
=> spdx: explain SHA1 usage

pkg/apk/apk/repo.go
The newly added path that fails when we're picking something that conflicts with something we already selected would do name=version instead of using the original constraint, which means it's wrong in cases where we use e.g. `<`.
Before:
│ we already selected "ruby3.2-fluentd-1.18"="1.18.0-r1" which conflicts with "ruby3.2-fluentd"="1.18"
After:
│ we already selected "ruby3.2-fluentd-1.18=1.18.0-r1" which conflicts with "ruby3.2-fluentd<1.18"
=> Improve conflict error

pkg/apk/signature/rsa.go, pkg/apk/signature/sign.go
Remove support for creating new SHA1 signatures.
Verification of SHA1 signatures remains until after Alpine migrates to
SHA256.
Using current melange, adding replace in go.mod to use this apko, and use the bypass environment variable to worse SHA1 signatures results in this runtime error:
```
SIGNING_DIGEST=SHA1 melange sign --signing-key *.rsa packages/x86_64/openssl-dev-3.4.0-r7.apk 
2025/01/25 03:45:52 INFO Processing apk packages/x86_64/openssl-dev-3.4.0-r7.apk
2025/01/25 03:45:52 ERRO creating sha1 signatures not supported
```
And similarly during package build
```
export SIGNING_DIGEST=SHA1
make package/wolfi-baselayout
2025/01/25 03:46:07 INFO   runtime:
2025/01/25 03:46:07 INFO     ca-certificates-bundle
2025/01/25 03:46:07 INFO   installed-size: 127332
2025/01/25 03:46:07 INFO …
```
=> apk/signature: remove support for creating new SHA1 signatures

pkg/sbom/generator/spdx/spdx.go
Add attributionText field, that can be empty, such that melange can
start setting it.
=> spdx: add attributionText field

pkg/apk/apk/cache.go, pkg/apk/apk/implementation.go, pkg/apk/expandapk/expandapk.go, pkg/paths/paths.go, pkg/paths/paths_test.go
Currently the cached files are `mv` to the final destination. While this works for a single process of `apko`, if there are multiple `apko` processes running, an existing file read can be invalidated if the file is later replaced (with another file with the same content).
This PR changes to leverage symlink instead. Since file reads in Go by default will follow symlink at file open time, overwriting the symlink won't invalidate existing reads.
We also check for the existence of the destination file before attempting to advertise the cached file, and we clean up the cached file if we didn't create a symlink at all. This is safe because there should be no way anyone else could read our version of the cache file.
I've tested with both NFS and gcs-fuse FS.
=> apko: make apk cache safer for multi-writers

pkg/apk/fs/fs.go, pkg/apk/fs/memfs.go, pkg/apk/fs/rwosfs.go, pkg/apk/fs/sub.go, pkg/tarfs/fs.go
Relates to: https://github.com/chainguard-dev/melange/pull/1804
Relates to: https://github.com/chainguard-dev/melange/issues/1731
This PR is part 1 of 2 (the second part is the Melange counterpart).
We need a SubFS implementation in order to correctly identify packages that are built by Melange when using the memFS filesystem.
Previously, we were doing `readlinkFS(pc.WorkspaceSubDir()` but now we need to maintain a FullFS type throughout the build. Using `fs.Sub` on the Melange side won't work because of this type assertion: https://github.com/chainguard-dev/apko/blob/3e63d01bb69480954b6040f5470197aead3f81da/pkg/apk/tarball/write.go#L250
If that assertion fails, then xattrs are not preserved.
If there's an easier way to orchestrate this outside of adding an entire SubFS implementation …
=> Add SubFS implementation for Melange

pkg/apk/expandapk/expandapk.go, pkg/apk/internal/tarfs/tarfs.go, pkg/build/build_implementation.go
This should help a lot with memory usage when building lots of things in the same process.
=> Use sync.Pools for allocations

pkg/apk/fs/rwosfs.go
I noticed that symlinks were being dropped when testing the changes in https://github.com/chainguard-dev/melange/pull/1836.
For example --
In `WorkspaceDir`:
```
.
melange-out
melange-out/greeter
melange-out/greeter/usr
melange-out/greeter/usr/bin
melange-out/greeter/usr/bin/greeter
melange-out/greeter-english
melange-out/greeter-english/usr
melange-out/greeter-english/usr/bin
melange-out/greeter-english/usr/bin/hello
melange-out/greeter-hawaiian
melange-out/greeter-hawaiian/usr
melange-out/greeter-hawaiian/usr/bin
melange-out/greeter-hawaiian/usr/bin/aloha
melange-out/greeter-latvian
melange-out/greeter-latvian/usr
melange-out/greeter-latvian/usr/bin
melange-out/greeter-latvian/usr/bin/sveiki
```
Opening `b.WorkspaceDir` via DirFS:
```
2025/03/12 12:40:44 INFO retrieving workspace from …
```
=> Preserve symlinks in DirFS

pkg/apk/apk/errors.go, pkg/apk/apk/install.go, pkg/tarfs/fs.go
Generally, this is a user Config error. However, since this can happen both during Config resolution, and building - it is hard for users using chainguard.dev/apko as a library to flag this to the user as a user error.
This PR converts these errors to use a type to make it easier for library users to do so.
=> returns structured errors when origins conflict

pkg/apk/apk/cache.go, pkg/apk/apk/implementation.go
I discovered this slowdown recently when trying to do a whole bunch of apko solves, which should be fast, but they were taking a while. I hadn't profiled where we spend our time since we added this key discovery mechanism, so I missed it.
This is probably incorrect for a very, very long-running process because we'd miss advertised key updates but I don't expect that to happen over long enough timespans to matter...
=> Cache DiscoverKeys calls via the shared cache

pkg/build/build.go
Melange will need access to an APK in order to instantiate a PkgResolver during its buildGuest routine.
=> build.go: Export APK from build context

internal/cli/build-minirootfs.go, pkg/apk/fs/memfs.go, pkg/build/busybox.go, pkg/tarfs/fs.go
Right now, the apko tar artifact is not reproducible, if I use `build-minirootfs` twice, on the same rendered yaml file (with locks) it still does not make two identical tars
This is because of `mkdir` and symlinks evaluated when assembling the rootfs:
As you can see this affects only directories and symlinks, but the files provided by the packages will keep their timestamp.
This PR will reset file's modinfo time, if it is in a range of the "last minute"
this is just an heuristic to detect stuff done by this process.
The result is now a fully reproducible tar.gz build, from the same locked yaml file:
thanks to @jonjohnsonjr there is a prettier solution
=> fix(tar): make writeTar reproducible for apko

pkg/paths/paths.go, pkg/paths/paths_test.go
Using relative paths, makes the cache relocatable, which helps when
bind-mounting / moving it about.
=> paths: prefer to use relative paths

pkg/apk/apk/implementation.go, pkg/apk/apk/package.go
We didn't actually need a whole implementation of `InstallablePackage` just to fetch a package. This PR creates less needy interfaces and inserts them when appropriate into our fetching implementation. This also adds a convenience function for creating a minimally fetchable package, which is useful if you don't already have such an implementation in the context of your code.
=> refactor: slim down interface requirements for fetching packages

pkg/build/sbom.go, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/spdx_test.go, pkg/sbom/options/options.go
Our image SBOMs currently embeds "the" (singular) layer digest and its
mediaType as a purl. For multi-layer images, this is no longer
reasonable. Instead, we'll include all the layers in the SBOM.
This is a bit tricky because the code in written to assume there is
always exactly one layer, but most of the tests pass exactly 0 layers,
and we want to support greater than one layer.
I've fixed up the tests and code to make the tests keep passing, but
we'll probably want to revisit what SBOMs look like when we start
shipping multiple layers (and write tests to enforce that).
=> For multi-layer images, include all layers

docs/build-process.md, pkg/build/build.go, pkg/build/build_implementation.go, pkg/build/tarball.go, pkg/build/tarball_test.go
Instead of writing out the entire layer in one shot, layerWriter exposes a tar.Writer so that it's possible to construct a layerWriter, write to it a bunch of times, then finalize the layerWriter to produce a layer.
This PR should be a no-op, but we'll take advantage of this for multiple layers when we walk the filesystem and have multiple possible layerWriters to choose from.
=> Use a lazy layerWriter for writing tar files

pkg/apk/apk/cache.go
Currently APKINDEX.tar.gz cache is not world readable, but the
individual apk streams are.
```
$ ls -latr https%3A%2F%2Fpackages.wolfi.dev%2Fos/aarch64/APKINDEX/*
lrwxrwxrwx 1 xnox xnox       14 Apr 13 23:23 'https%3A%2F%2Fpackages.wolfi.dev%2Fos/aarch64/APKINDEX/GY3WENJZGRTGEYJVHE2TQZBTGQ2GMMTFGNRTMMLGGRSTONRQGVQQ====.tar.gz' -> 3496108094.tmp
-rw------- 1 xnox xnox 11595802 Apr 13 23:23  https%3A%2F%2Fpackages.wolfi.dev%2Fos/aarch64/APKINDEX/3496108094.tmp
$ ls -latr https%3A%2F%2Fpackages.wolfi.dev%2Fos/aarch64/git-2.49.0-r1/expand-apk821189521/
total 27032
-rw-rw-r-- 1 xnox xnox     5550 Apr 13 23:23 stream-0.tar.gz
drwx------ 2 xnox xnox     4096 Apr 13 23:23 .
-rw-rw-r-- 1 xnox xnox  9096589 Apr 13 23:23 stream-1.tar.gz
-rw-rw-r-- 1 xnox xnox 18566144 Apr 13 23:23 stream-1.tar …
```
=> apk: fix cached APKINDEX to be world readable

pkg/apk/apk/version.go, pkg/apk/apk/version_test.go
Currently, packages that ship shared libraries in the archive will have versioned provides for those shlibs.  These versions are calculated from the soname version, e.g.:
```
provides = so:libfoo.so.6=6
```
With the advent of
https://github.com/chainguard-dev/melange/pull/1871, the new versions will reflect the package version.  This can introduce a package resolution problem when the soname version is greater than the package version, e.g.:
```
libfoo-4.0-r1
provides = so:libfoo.so.6=6
```
vs.
```
libfoo-4.0-r2
provides = so:libfoo.so.6=4.0-r2
```
It's clear that we should select libfoo-4.0-r2 as the most recent package, but apko will currently select libfoo-4.0-r1 instead.
The solution proposed here is to ignore the versioned depends/provides *iff* the version that comes after "=" does …
=> version.go: Ignore soname-versioned provides/depends for shlibs

internal/cli/publish_test.go, internal/cli/testdata/layering.yaml, pkg/apk/apk/implementation.go, pkg/apk/apk/install_test.go, pkg/apk/apk/repo.go, pkg/apk/apk/repo_test.go, pkg/apk/apk/version.go, pkg/apk/apk/version_test.go, pkg/build/build.go, pkg/build/build_implementation.go, pkg/build/build_test.go, pkg/build/layers.go, pkg/build/layers_test.go, pkg/build/oci/image.go, pkg/build/types/image_configuration.go, pkg/build/types/schema.json, pkg/build/types/types.go, pkg/tarfs/fs.go
This uses a "simple" strategy of merging origins and replaces, then
taking the largest $budget groups of packages, merging the remainder.
This should not have any effect on apko configs that don't opt into
layering via the "layering" field, which is marked experimental:
```yaml
layering:
strategy: "origin"
budget: 10
```
This will split packages into up to 10 different layers (+1 for
everything that doesn't belong to a package).
=> Implement generic layering

pkg/apk/apk/implementation.go
Addresses: https://github.com/chainguard-dev/apko/issues/1330
Apko in offline mode was attempting to fetch keys... The code in case of
offline mode was doing a shortcut to check whether a file exists.
But the code was wrapped in a retryable http wrapper that introduced ~(4 x 30s) jitter
into the process.
In this PR -> in offline mode -> we turn off the retries around the fetch.
This way -> if file exists in the cache -> we use it.
If it doesn't - we accept it. And most likely we will use key provided explicitly using --extra_keys flag.
After fix the process finishes instantly: 
```
apko % go run . build --offline ../../container-images/bazel/gcbi/baseimages/static_glibc.apko.yaml foo /tmp
2025/04/10 15:44:18 WARN ignoring missing keys for …
```
=> Do not retry with jitter when discoveringKeys in offline mode.

internal/cli/lock.go, pkg/apk/apk/implementation.go, pkg/apk/apk/resolveapk.go, pkg/apk/expandapk/expandapk.go
Speedup and code alignment of 'apko-lock'. 
Before this change 'apko lock' was downloading all the packages every time and not utilising cacheDir.
After this change the cache is working. Also the fix should speedup apko resolution of packages for regular `apko build` (not lockaed) as
now `ResolveWorld` and Installation are sharing downloaded packages (and code).
Fixes: https://github.com/chainguard-dev/apko/issues/1475
=> CacheDir support for `apko lock`

pkg/apk/apk/cache.go
This causes issues on some filesystem types.
See https://github.com/chainguard-dev/internal-dev/issues/11366
=> apk cache: ignore error on cache tmpfile chmod

pkg/build/types/schema.json, pkg/build/types/types.go
This is opt-in but I'm sufficiently convinced this is ready to pull into terraform-provider-apko, which ignores experimental fields.
=> Drop experimental tag from layering

pkg/apk/apk/apkindex_test.go, pkg/apk/apk/index.go
When download keys from Artifactory, such URLs for e.g. are being used:
https://artifactory.{redacted}.com/artifactory/api/security/keypair/public/repositories/development-wolfi-virtual
The URL returns:
```
content-disposition: attachment; filename=keyname.rsa.pub ,
```
The keyname can be configured to be e.g. 'development-wolfi-virtual'.
Before this patch there was a mismatch on INDEX files signatures verification.
The verification expected: development-wolfi-virtual.rsa.pub,
but as Apko ignores the content-disposition header, it observes just `development-wolfi-virtual.rsa.pub`
that does not match.
In this PR I enabled matching that recognized development-wolfi-virtual ~= development-wolfi-virtual.rsa.pub.
Alternatively we could consider:
a) changing fetcher to recognize …
=> Apko keyrings to recognize key suffixes when lost during fetch:

go.mod, pkg/apk/auth/auth.go
Allows for easier reuse of credentials being passed in from another source.
=> auth: Add oauth2.TokenSource auth provider

README.md
Current URL isn't valid (`issue` -> `issues`)
=> README: fix url typo

README.md
To reduce confusion about our commercial support obligations around apko, I'd like to reword this.
=> Remove link to "support"

pkg/build/lock.go, pkg/build/lock_test.go
This can panic if called incorrectly, return an empty list instead.
=> Guard against empty inputs list in unify()

pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/spdx_test.go, pkg/sbom/generator/spdx/testdata/apk_sboms/_generate.sh, pkg/sbom/generator/spdx/testdata/apk_sboms/unbound-1.23.0-r0.spdx.json, pkg/sbom/generator/spdx/testdata/apk_sboms/unbound-config-1.23.0-r0.spdx.json, pkg/sbom/generator/spdx/testdata/apk_sboms/unbound-libs-1.23.0-r0.spdx.json, pkg/sbom/generator/spdx/testdata/expected_image_sboms/unbound-package-dedupe.spdx.json
Prune a whole load of code out of the processing of APK SBOM's into the Image SBOM; this ensures that the SBOM for the Image is complete and we don't accidentally prune packages with the same name (which is not guaranteed to be unique).
I'm sure there is history here and I'm not 100% sure I understand why a generated SPDXRef was pushed to the Image SBOM document, only to be removed at the end of the APK SBOM processing.  Testing looks good based on comparing current APKO release with this PR.
Add a test case based on unbound to validate.
Fixes #1507
Signed-off-by: James Page <james.page@chainguard.dev>
=> sbom: resolve issues with missing/invalid image SBOM information

pkg/apk/expandapk/expandapk.go
I'm not sure where the numbered error codes comes from, I think it was ported somewhat literally from apk's code.
=> improve error messages in expandApk

internal/cli/testdata/golden/sboms/sbom-aarch64.spdx.json, internal/cli/testdata/golden/sboms/sbom-x86_64.spdx.json, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/testdata/expected_image_sboms/custom-license.spdx.json, pkg/sbom/generator/spdx/testdata/expected_image_sboms/no-supplier.spdx.json, pkg/sbom/generator/spdx/testdata/expected_image_sboms/package-deduplicating.spdx.json, pkg/sbom/generator/spdx/testdata/expected_image_sboms/unbound-package-dedupe.spdx.json
We are missing some information in our image SBOMs that cause trivy to generate warnings. The missing piece is a package declaring what operating system our images are using.
=> Add an OperatingSystem package to our image SBOMs

pkg/build/build.go, pkg/build/build_implementation.go, pkg/build/layer_cache_test.go
Carrying on from #1667 
This adds the compression cache, so that if `Digest()` is called and there's already a cached copy of the diffID -> digest available, we'll use it, instead of computing it again. Same with `Size()`.
If the pre-computed compressed digest is already present in the registry for example, the resulting `HEAD` request's `200` will tell us we don't need to compress anything at all, and we can skip a lot of work.
If the digest isn't in the registry already, we'll compress and compute it like we did before, but that should happen a lot less often with this cache.
=> Lazily compress layers, maintain diffID -> digest cache

.github/workflows/release.yaml
Enable cronned automatic releases as well as on demand release.
This removes need to manually create and push tags.
=> github: copy release workflow from melange

pkg/build/build.go, pkg/build/layer_cache_test.go
I have a theory that sometimes this can get called concurrently and it would truncate the compressed file which could invalidate the digest.
=> Wrap lazy compress() in a mutex

pkg/build/build_implementation.go
`/etc/ld.so.cache` is created with `os.Create` internally which creates a file with `0666` permissions ([dag](https://oci.dag.dev/fs/cgr.dev/chainguard/bash@sha256:b53e7f70cc3ac51b9c2a52fc4bfeb264ca6a560919a3e8228639e6890247196d/etc/))
```bash
-rw-rw-rw- 0/0            6528 1970-01-01 00:00 ld.so.cache
```
This PR lowers the permission of file to `0644`
=> fix: /etc/ld.so.cache file permissions

pkg/apk/fs/memfs.go, pkg/apk/fs/memfs_test.go, pkg/tarfs/fs.go, pkg/tarfs/fs_test.go
The unsafe defaults for apko's DirFS implementations were the root cause for the ld.so.cache mode 0o666 issue. Unlike os.Create(), these implementations generally don't honor umask(), so make them have safer defaults, and require that things that need less restrictive permissions change them after the fact.
v2: add testcase for MemFS
v2: add testcase for TarFS
=> DirFS implementations: make Create() default to safer permissions

.github/workflows/verify.yaml
golangci-lint does not yet support golang 1.25 (stable), so the verify workflow would fail with:
> Running [/path/golangci-lint run] in [/home/runner/work/apko/apko] ...
> panic: file requires newer Go version go1.25 (application built with go1.24) [recovered]
>   panic: file requires newer Go version go1.25 (application built with go1.24)
=> ci - make verify workflow use golang 1.24 for compat with golangci-lint

.github/workflows/examples-test.yaml, examples/on_top_of_base/build.sh, pkg/apk/apk/implementation.go, pkg/apk/apk/implementation_test.go
When building on a base image with usrmerge layout, we should not try to create the `lib` directory, because the provided packages already has it.
To avoid making this decision based on actually looking at the base image's file system, we will just look at the install packages to see if it was one that provides a usrmerge layout. 
Also add a "examples test" to run the sample's shell script to confirm fix.
=> bug-fix: handles usrmerge base image correctly

pkg/apk/fs/rwosfs.go, pkg/apk/fs/rwosfs_test.go
The DirFS implementation of open() attempts to perform an os.Open() on the underlying file and if a permissions error is returned, attempts to work around this by changing the permissions on the file and then retrying the os.Open() call. If this succeeds, the original permssions are saved to be reset when the File object is Close()ed.
However, the Close() operation was performing the restorative chmod operation on the saved name of the file, which is the *basename* of the original file, which thus results in the chmod being performed on `$PWD/$(basename NAME)`.
This bug is triggered in melange's qemu runner due to Wolfi's base package permissions on `/etc/shadow` getting changed to mode 0000; when melange would attempt to build the cpio initrd for the qemu guest, apko's …
=> DirFS: correct resetting of permissions
