chainguard-dev/apko

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/verify.yml, .gitignore, .golangci.yml
- add dependabot
- add initial ci for build/test
- add golangci-lint
=> Add initial ci jobs

cmd/apko/cli/publish.go
Signed-off-by: Jason Hall <jasonhall@redhat.com>
Maybe fixes #28
=> Print published image digest to stdout

NEWS.md, pkg/build/apk.go, pkg/build/build.go, pkg/build/executor.go, pkg/cli/build-minirootfs.go, pkg/cli/build.go, pkg/cli/publish.go
As suggested from an IRC conversation with @boomanaiden154 on `#alpine-devel`.
=> support using proot for rootless image builds

pkg/build/executor.go, pkg/build/image_builder.go
=> emulate busybox install when running under proot

pkg/build/build.go, pkg/cli/build-minirootfs.go, pkg/cli/build.go, pkg/cli/publish.go
make it more flexible and easier to add new options and reduce noise the method signature.
=> refactor: use functional options for the build.Context

.editorconfig, .github/workflows/verify.yaml, .gitignore
Signed-off-by: panekj <me@panekj.dev>
=> Small improvements

pkg/build/accounts.go, pkg/passwd/group.go, pkg/passwd/group_test.go, pkg/passwd/passwd.go, pkg/passwd/passwd_test.go
Closes https://github.com/chainguard-dev/apko/issues/71
=> fix: create passwd/group file if missing

pkg/build/build.go
this is needed for Melange (and Dagger will probably find it helpful too)
=> pkg/build: add build.WithImageConfiguration

pkg/tarball/tarball.go
needed to allow Melange to generate tarballs with files owned by root
without having to actually be root
=> pkg/tarball: add UID/GID override feature

pkg/tarball/tarball.go
=> pkg/tarball: add override uname and gname feature to supplement UID/GID override

go.mod, go.sum, pkg/sbom/generator/generator.go, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/generator/spdx/spdx_test.go, pkg/sbom/sbom.go
This commit adds the initial SPDX support to the SBOM package. This initial iteration still lacks a more ample test coverage and the data in the SBOM can be improved. Yet this first version outputs valid SPDX encoded in json.
Some details still to work in follow ups:
* purls need work to add the complete data. All in all some pieces still missing but its 80% there.
* tests need more coverage still
* package author information is weird
* some json values need `omitifemtpy`
A sample of the produced SBOM:
```json
{
"SPDXID": "SPDXRef-DOCUMENT",
"name": "apko-ba4d4c06-5125-40f2-8f88-fdb333a59054",
"spdxVersion": "SPDX-2.2",
"creationInfo": {
"created": "1970-01-01T00:00:00Z",
"creators": [
"Tool: apko (v0.0.0)",
"Organization: Chainguard, Inc"
],
"licenseListVersion": "3.16"
},
"dataLicense": …
```
=> Initial SPDX support

pkg/build/build.go, pkg/cli/build-minirootfs.go, pkg/cli/build.go, pkg/exec/cmd.go, pkg/exec/exec.go
Needed for multiarch support, closes #81.
=> support qemu-binfmt emulation with proot

pkg/build/apk.go, pkg/build/apk_test.go, pkg/build/build.go, pkg/build/image_builder.go, pkg/build/oci/oci.go, pkg/build/sbom.go, pkg/build/types/image_configuration.go, pkg/build/validate.go, pkg/cli/build.go, pkg/cli/publish.go, pkg/exec/cmd.go, pkg/exec/exec.go, pkg/s6/s6.go, pkg/s6/supervision_tree.go
Part of the work needed to pick up and merge #90 before release.
=> refactor logging

pkg/build/build.go, pkg/build/sbom.go, pkg/build/types/types.go, pkg/cli/build.go, pkg/cli/publish.go, pkg/sbom/sbom.go
Various multiarch refactorings needed to make it more robust.
Closes: #76
CC @imjasonh, @puerco
=> refactor multiarch, add parallelization, improve logging

.github/workflows/codeql.yaml
This PR implements [CodeQL](https://github.com/github/codeql-action) into pipeline.
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
Co-authored-by: Batuhan <batuhan.apaydin@trendyol.com>
=> ci: integrate codeql

pkg/build/accounts.go
=> build: accounts: ensure home directory gets created and improve logging

.github/workflows/build.yaml, .github/workflows/mink-e2e.yaml, .github/workflows/release.yaml, .github/workflows/verify.yaml
- Updates on CI for goreleaser/ko/golangci-lint
=> Updates on CI for goreleaser/ko/golangci-lint

examples/apko-devenv.yaml
There's a nice makefile, so let's use it from the devenv.
=> Add make to devtools

examples/nginx-rootless.yaml, examples/nginx.yaml, pkg/build/build_implementation.go, pkg/build/buildfakes/fake_build_implementation.go, pkg/build/paths.go, pkg/build/types/types.go
=> Add configurable path mutations

README.md, docs/apko_file.md
Still needs work, in particular note things marked TK. Will continue tomorrow, just wanted to put this up in case people wanted to take a look.
=> First pass at apko docs.

docs/apko_file.md
=> Fix command syntax in docs

docs/apko_file.md, go.mod, go.sum, pkg/build/oci/oci.go, pkg/build/types/types.go
=> add explicit shell fragment support for entrypoint, make command a bare command

pkg/build/os-release.go
Related to aquasecurity/fanal#468.
=> os-release: generate legacy vendor release files

pkg/build/accounts.go
These are:
1. `root` doesn't have a home directory in most of the distroless images,
2. `chown` the home directory so the user actually owns their home directory,
3. don't grant other users permissions to user home directories.
Here's an example from the git image built with this:
```
$ tar tvf baz.tar  | grep '[-]---' | grep '^d'
drwx------  0 root   root        0 Dec 31  1969 etc/X11
drwx------  0 xfs    xfs         0 Dec 31  1969 etc/X11/fs
drwx------  0 root   root        0 Dec 31  1969 home
drwx------  0 65532  65532       0 Dec 31  1969 home/nonroot
drwx------  0 root   root        0 Dec 31  1969 root
drwx------  0 cyrus  mail        0 Dec 31  1969 usr/cyrus
drwx------  0 games  games       0 Dec 31  1969 usr/games
drwx------  0 news   news        0 Dec 31  1969 usr/lib/news …
```
=> This fixes a handful of issues with home directories.

.github/workflows/add-issues.yml
updating the action to:
- Retrieve project and custom field details.
- Use issue to create new project item.
- Update custom field date /w created on timestamp.
- Update custom field tent-pole w/ value Images.
- Update custom field issue priority w/ value P2 (default priority of new issues).
=> updating action to include more steps.

pkg/cli/commands.go, pkg/cli/show-config.go
=> cli: add show-config command

docs/faq.md
=> First draft of FAQ.

.github/workflows/release.yaml, Makefile
Fixes #142 
Example workflow: https://github.com/imjasonh/apko/runs/6710091200?check_suite_focus=true
Example release: https://github.com/imjasonh/apko/releases/tag/v0.0.0-fake.4
(NB: the workflow fails in other legs due to some unrelated issue with Fulcio)
=> Generate and release Tekton Task

hack/make-devenv.sh
Hack script needs newer version of alpine, so it can get a newer version of Go, so we can build apko...
=> Update version of alpine.

README.md
Adding a period makes the bullets under features consistent. I also found, I think, a typo.
=> Fix minor issues with README

go.mod, go.sum, internal/cli/build-minirootfs.go, internal/cli/build.go, internal/cli/publish.go, pkg/apk/apk.go, pkg/apk/apk_implementation.go, pkg/apk/apk_unit_test.go, pkg/build/accounts.go, pkg/build/build.go, pkg/build/build_implementation.go, pkg/build/oci/oci.go, pkg/build/options.go, pkg/build/types/image_configuration.go, pkg/build/validate.go, pkg/exec/exec.go, pkg/exec/exec_test.go, pkg/exec/exec_unit_test.go, pkg/exec/execfakes/fake_executor_implementation.go, pkg/exec/implementation.go, pkg/exec/implementation_test.go, pkg/options/options.go, pkg/s6/s6.go, pkg/s6/supervision_tree.go, pkg/sbom/sbomfakes/fake_sbom_implementation.go
Use logrus for logging instead of the Go logging module which is not that great to use.
=> use logrus for logging

go.mod, go.sum, pkg/build/oci/oci.go, pkg/build/options.go, pkg/build/types/image_configuration.go, pkg/build/types/types.go, pkg/vcs/vcs.go
Probe for Git repositories relative to the apko.yaml file and set a VCS URL annotation if we find one.
Closes #231!
=> Detect VCS URLs and set org.opencontainers.image.source if found

pkg/build/oci/oci.go, pkg/build/types/types.go
=> add working directory setting

docs/apko_file.md, examples/nginx.yaml
Haven't tested this yet.
Signed-off-by: Adrian Mouat <adrian@chainguard.dev>
=> Add docs for work-dir.

pkg/build/oci/oci.go
This should get #301 ... sorted :wink:
=> Sort environment variables to ensure image is reproducible

README.md
=> Update README.md to reflect build & install

internal/cli/publish.go
This should be faster than publishing again
=> Copy image index to additional tags instead of publishing again

internal/cli/publish.go, pkg/build/oci/oci.go
=> Pass in auth when copying image tags

internal/cli/publish.go
=> Rollback tagging change to unblock builds

internal/cli/publish.go
=> Use copy for additional tags

README.md
This PR brings some minor updates to the README, including basic debug instructions.
=> Minor updates to readme, including debug info

.gitignore, pkg/build/build_implementation.go, pkg/build/errors.go, pkg/build/os-release.go
=> Do not generate /etc/os-release if already present

pkg/build/types/types.go
Signed-off-by: James Rawlings <jrawlings@chainguard.dev>
=> add yaml tags to remove empty values when marshalling

docs/apko_file.md, internal/cli/publish.go, pkg/build/oci/oci.go
Fixes https://github.com/chainguard-dev/apko/issues/352
=> add annotations to indexes, separate repo and revision annotations, document

.github/dependabot.yml
=> run dependabot daily

.github/workflows/add-issues.yml, .github/workflows/build.yaml, .github/workflows/codeql.yaml, .github/workflows/go-tests.yaml, .github/workflows/mink-e2e.yaml, .github/workflows/release.yaml, .github/workflows/verify.yaml, .golangci.yml, go.mod, pkg/build/oci/oci.go, pkg/sbom/generator/spdx/spdx.go
=> upgrade to go1.19

pkg/sbom/generator/spdx/spdx.go
- remove not used return error variable
follow up of https://github.com/chainguard-dev/apko/pull/369#discussion_r984588453
=> remove not used return error variable

pkg/sbom/generator/cyclonedx/cyclonedx.go, pkg/sbom/generator/spdx/spdx.go, pkg/sbom/options/options.go
This PR fixes a problem where apko would not encode properly some values in JSON values.
=> Fix unecoded characters in purls

internal/cli/publish.go, pkg/apk/apk.go, pkg/apk/apk_test.go, pkg/build/options.go, pkg/options/options.go
Resolves https://github.com/chainguard-dev/apko/issues/403
=> Add ability to get stemmed version tags

docs/build-process.md, pkg/build/build.go, pkg/build/build_implementation.go
As described. Ready for some feedback.
=> Document build process

examples/wolfi-base.yaml, pkg/build/build_implementation.go, pkg/build/os-release.go, pkg/build/types/image_configuration.go, pkg/sbom/generator/spdx/spdx_test.go, pkg/sbom/sbom.go, pkg/sbom/sbom_unit_test.go
Fixes https://github.com/chainguard-dev/apko/issues/399
=> Read /etc/os-release from the image to generate SBOM purls

internal/cli/publish.go, pkg/build/oci/oci.go, pkg/build/options.go, pkg/options/options.go
Add the ability to write all target tags to a file vs. publishing them
=> Add --stage-tags flag to apko publish

pkg/apk/impl/repo.go, pkg/apk/impl/repo_test.go, pkg/apk/impl/version.go, pkg/apk/impl/version_test.go
Fixes #470 
@kaniini can you validate that this actually resolves what you were looking for? Specifically, look at the test case for version resolution [here](https://github.com/chainguard-dev/apko/pull/473/files#diff-0fe948ffc19f6666deee62dfea127804fc3033d1c7ad2971b1178715a50735bdR94).
=> add versions with constraints

pkg/apk/impl/fs/rwosfs.go
The case-sensitive extension for filesystems in rwosfs has a func `createOnDisk()` that determines (only when running on an underlying filesystem that is case-insensitive) whether a particular filename should be created on disk (first one of this name in any case) or in the memory overrides.
`createOnDisk()` misses the case where that exact file _already_ exists on disk. It handles it just fine when the file does not exist, or when it is a conflict, e.g. a new file named `FOO` when one named `foo` already exists. But it fails when it tries to open `foo` and `foo` already exists. Whether the open behaviour will cause a problem is an issue for the `OpenFile()` that eventually gets called, and handles it correctly.
This PR fixes that issue.
=> handle when file already exists

pkg/apk/impl/implementation.go
Signed-off-by: Ariadne Conill <ariadne@chainguard.dev>
=> apk: implementation: tolerate directories already existing

internal/cli/publish.go
The problem was that, during the later sbom phase, it was regenerating a `TempDir()`, which was distinct from where the tar files actually were.
This has a lot of duplication with the multi-arch build changes in #499 (actually, I had to solve those problems there, so I just copied my solutions from there). We should get this in for the fix, then if we want 499, get it in, and then rationalize the whole thing.
=> carry through layer tgz files in publish

pkg/apk/impl/repo.go
This is an issue for dependencies that are not names but in the "provides" list. Previously, it just took the last one, which could be different each time.
Here, it improves, if not completes it:
1. If the same package we are using provides the dependency, then nothing to add
2. If another package that provides the dependency has the same origin as our package, use that
3. Otherwise, use the first one on the list
The last step still isn't great, but it is an improvement as we add the first 2 steps. 
@kaniini pointed out that the apk-tools logic is:
> if a package is already enqueued to be installed, and it provides something, then that package will be considered first for the provided dependency
We should do that, but in a later PR.
=> handle multiple packages providing same files sanely

pkg/apk/impl/repo.go, pkg/apk/impl/repo_test.go
This is not complete yet, but a step forward.
It adds the sorting of dependent package to include:
* matching origin with the comparison package
* matching repository with the comparison package
* matching origins with any existing
=> better dependency resolution sorting logic

pkg/apk/impl/repo.go
It was causing a SIGSEGV in some cases.
=> improperly passing package to dependenciesMap

pkg/apk/impl/repo.go
When there are multiple packages that can satisfy a dependency, we already prioritize those already installed, but we miss those that have not _yet_ been installed but have been explicitly requested.
This ensures we catch any explicitly requested.
=> properly prioritize explicitly requested packages

pkg/apk/impl/repo.go
In PR #520 we prioritized packages that were explicitly requested. This allowed the dependency tree builder to choose between versions, when one already was explicitly requested.
However, this caused the package order builder to think that a package that was priority, and thus _would_ be installed, actually _was_ in the list, when it was not yet, messing up the order.
This fixes it by separating between "here are packages we know about" and "here are packages tracked to be installed". It returns the order to the right thing.
=> track known dependencies and tracked dependencies separately

pkg/apk/impl/repo.go
It only supports exact matches, either generic name or precise version:
```
i:foo bar=1.36.0-r1
```
If we care about more complex compare cases, we can add them later.
=> begin support for installif

pkg/build/busybox.go
we missed some. Reran `busybox --list-full` to get the links and sort them
=> ensure busybox links are complete

.github/workflows/build-samples.yml
This is at least partially a test of whether apko can actually run from Windows.
If it does work, we should keep testing to ensure we don't regress.
=> ci: run apko from multiple host OSes

pkg/apk/impl/version.go
=> apk: version: filterPackages: fall back to comparing provided versions when the package version itself is mismatched

pkg/apk/impl/fs/rwosfs.go
rwosfs has 2 functions for checking if a specific file's case-sensitive version is on-disk. One only checks, and one checks and, if it should be, updates the list.
We used the "check-only" version when creating a symlink, which is wrong. This updates it.
Fixes #580
=> record when writing symlinks to case-sensitive

internal/cli/commands.go
Previously, https://github.com/chainguard-dev/melange/pull/378
=> feat: send useragent in HTTP requests

pkg/apk/impl/fs/memfs.go, pkg/apk/impl/fs/memfs_test.go
The memfs handled symlinks as the leaf of the path, but not in the middle. For example, it could handle:
```
/a/b/c -> d
```
but not:
```
/usr/lib64 -> lib
```
and then process the file at `/usr/lib64/foo`.
This fixes it. It also adds a test for that specific use case.
=> fix mid-level symlinks for native-memfs

pkg/apk/impl/repo.go, pkg/apk/impl/repo_test.go
`ResolvePackage()` finds all packages that match the required package and constraint, sorts them in descending priority, then returns the first one.
It is useful to return _all_ of the packages that match the constraints, and let the caller decide if they want just the first.
Granted, this changes the API, but it is used only twice here in apko (changed in this PR as well), and since `ResolvePackage()` went in not a few days ago, and nothing else is using it yet, this is a good time to change it.
No logic change involved other than that.
=> return all matches for PkgResolver.ResolvePackage

pkg/apk/impl/installed.go, pkg/apk/impl/installed_test.go
It was just sorting by name. This mean that you could (and did) end up with entires in `lib/apk/db/installed` like this.
Assuming your actual files are (directories end in `/`):
```
etc/
etc/one
etc/foo/
etc/foo/bar
```
```
F:etc/
F:etc/foo
R:bar
R:one
```
When what you really want is:
```
F:etc/
R:one
F:etc/foo
R:bar
```
Added a test as well, of course.
=> better sort order for packages when writing to apk/db/installed

go.mod, go.sum, pkg/apk/impl/implementation.go, pkg/apk/impl/install.go, pkg/apk/impl/install_test.go
Packages with replaces entries can replace files in other packages as if they had the same origin.
=> apk: install: add support for replaces

internal/cli/publish.go, pkg/build/oci/oci.go
This is causing melange to pull in a bunch of deps it doesn't need.
=> Move default remote options out of library

internal/cli/publish.go, internal/cli/publish_test.go, pkg/log/adapter.go
Adding this test as-is so that the race-detection fixing stuff can be reviewed separately from the actual test code.
I am unsure how this test passes.
Fixes https://github.com/chainguard-dev/apko/issues/717
=> Add a no-op test for PublishCmd

pkg/build/oci/oci.go, pkg/build/oci/oci_test.go
Fixes https://github.com/chainguard-dev/apko/issues/682
Also add a test of this behavior.
=> change how default envs are set

go.mod, go.sum
@found-it I would be curious whether with this you get consistent timestamps with our images 🤞
=> Pull in https://gitlab.alpinelinux.org/alpine/go/-/merge_requests/25

internal/cli/show-packages.go
* ~Pulls in the reduced redundancy in package version logging; does not affect implementation algorithm, just logging info.~  this already was covered in #746 
* Adds multiple output formats for `show-packages`, as well as support for go templates
=> improved show-packages output

pkg/build/build_implementation.go
This reduces BuildTarball latency by ~10%.
=> Add 4MiB bufio for pgzip

pkg/apk/apk.go
As suggested by @kaniini [here](https://github.com/chainguard-dev/apko/issues/788#issuecomment-1627660314)
We already fixed the crashing in #796. This handles changes the logic as follows:
Current:
* if `--cache-dir` set, use that
* if can determine default cache dir via `os.UserCacheDir()`, use that
* return an error
Changed:
* if `--cache-dir` set, use that
* if can determine default cache dir via `os.UserCacheDir()`, use that
* proceed with no cache, logging a warning to the user
=> work with no cache when cache-dir is not set and HOME is not set

go.mod, go.sum
to pull in - https://github.com/chainguard-dev/go-apk/pull/79
=> bump go-apk

internal/cli/build.go, internal/cli/publish.go, pkg/apk/apk.go, pkg/apk/apk_test.go, pkg/build/build_implementation.go
Fixes #808 
This does the following:
1. Pulls the `additionalTags()` discovery out of the `buildImage` section
2. Has `buildImage()` report back on all installed packages, which is a good artifact relevant to build stage: "I built this image for this arch, here are the packages I installed"
3. Runs through those packages by arch, and checks that the versions are identical, per [this comment](https://github.com/chainguard-dev/apko/issues/808#issuecomment-1646332265), else error
4. Use those now-verified-as-identical tags for the additional tags
In doing so, it also moved some funcs that used to just rely on passing `build.Context.Options` and knowing what they were, to explicit vars. This makes the signature a bit longer, but easier to understand, and no longer dependent on some build …
=> restore handling of packageTag CLI flags for publish

pkg/sbom/generator/spdx/spdx.go
The previous implementation had ~quadratic runtime with the number of elements we needed to copy. This does it all in one pass.
Fixes https://github.com/chainguard-dev/apko/issues/799
=> Optimize SBOM generation

internal/cli/build.go
This allows us to write out images in a much more efficient format for other tools to consume.
Just writing the whole index as index.json is the simplest thing we could do, and we end up dropping the image tag, but I think this is a fine place to start.
Fixes https://github.com/chainguard-dev/apko/issues/74
Closes https://github.com/chainguard-dev/apko/pull/769
@vito apologies for not seeing your outstanding PR, just folded it into this and rebased.
=> Write index as layout if target is a directory

NEWS.md
v0.10.1 never happened apparently
=> Update NEWS.md for v0.11.0

internal/cli/dot.go
This is hardly correct but it was useful enough to help me debug an issue with how we're solving.
=> Try to approximate ~ in apko dot

go.mod, go.sum, internal/gen-jsonschema/generate.go, internal/gen-jsonschema/main.go, pkg/build/types/schema.json
Allows for generation of json schema for apko config. We should wire this up to CI to make sure this is kept up to date in another PR.
=> Add binary to generate json schema.

pkg/tarfs/fs.go
Before this, when writing a new file, we allow a new package to install files over any packages that it replaces, but we failed to check the other direction.
If an already installed packages replaces a package we want to install, we shouldn't fail if there are conflicting files. Instead, we should just skip writing any files in the replaced package.
This way we don't rely on the installation order for replaces checks to work as expected.
=> Allow existing packages to replace installed pkg

.github/workflows/verify.yaml, Makefile
Adds makefile target + CI verify check to ensure jsonschema stays up to date.
=> Ensure jsonschema is kept up to date.

internal/cli/dot.go, internal/cli/show-config.go, internal/cli/show-packages.go
Also drop show-packages printing arch to stdout so I can use it.
=> Plumb offline flags around more

pkg/apk/fs/memfs.go, pkg/build/busybox.go
This is causing issues with busybox.
=> Skip over "." when creating directories

internal/cli/build-minirootfs.go, internal/cli/build.go, internal/cli/publish.go, pkg/apk/apk/implementation.go, pkg/apk/apk/options.go, pkg/build/build.go, pkg/build/options.go, pkg/options/options.go
This PR is to expose ignoreSignatures functionality to CLI and library consumers (Resolves https://github.com/chainguard-dev/apko/issues/888).
I'll be following this up with a PR to melange to consume this functionality.
This is my first PR to the project, so please don't hesitate to let me know if there's any project/style/etc preferences that I should keep in mind for future contributions. 
Thanks
=> Expose ignoreSignatures functionality to CLI and library consumers

internal/cli/show-packages.go, pkg/build/multi.go
In the terraform module, we call BuildPackageList for each arch: https://github.com/chainguard-dev/terraform-provider-apko/blob/812478b999411c183e87fefb9a9ece9fe7e8f2c1/internal/provider/config_data_source.go#L239
And then use that package list to actually build the image, so we separate the solving from the building.
This bypasses https://github.com/chainguard-dev/apko/pull/1180 which does this multi-arch constraining through a different entrypoint.
This adds another method to the multi-arch stuff that we can opt into for just the solve part.
To demonstrate this, I made `show-packages` use it:
```
diff --git a/examples/wolfi-base.yaml b/examples/wolfi-base.yaml
index d3ca2b8..0f0e979 100644
--- a/examples/wolfi-base.yaml
+++ b/examples/wolfi-base.yaml
@@ -4,7 +4,7 @@ contents: …
```
=> Add build.MultiArch.BuildPackageLists

pkg/tarfs/fs.go, pkg/tarfs/fs_test.go
Fixes https://github.com/chainguard-dev/apko/issues/1223
=> Fix replacing symlinks

pkg/apk/auth/chainguard.go
So we know which path weird errors are coming from.
=> auth: Wrap errors

go.mod, go.sum, pkg/apk/apk/cache.go, pkg/apk/apk/implementation.go, pkg/apk/apk/index.go
Reverts chainguard-dev/apko#1259
=> Revert "drop dependency on go.lsp.dev/uri"

pkg/apk/apk/implementation.go
I want to use this in wolfictl but it's hidden inside InitDB.
=> Expose DiscoverKeys

pkg/apk/apk/implementation.go
This changes the return type a bit but I'll fix that in wolfictl.
=> Keep standalone DiscoverKeys function

pkg/apk/auth/auth.go
```
token aud ([https://apk.cgr.dev]) does not match expectations ([apk.cgr.dev])
```
=> set audience correctly, no https

pkg/build/build.go
In trying to debug why we kept hanging when we uploading to the registry, I discovered that wrapping the os.File with something that logged each io.Read call made the problem go away. That made me think there was an inssue in the os.File WriteTo implementation, but I was wrong. Instead, the issue is in an optimization in net/http that uses sendfile if the request's Body is an os.File.
This wrapper just makes the os.File check fail so that we don't try to use sendfile at all. This will make perf a little bit worse in some situations, but we are not bottlenecked on reading from disk, so I'm not worried about it.
=> Work around sendfile bug

pkg/build/oci/index.go
`ic.Annotations` can be updated by outside callers, so instead of updating it in-place we should make a copy and use that for each image we build and annotate.
Also: don't set created annotation if it's not an OCI index (this was a bug previously, only affecting docker-typed manifests, which we don't use)
Previously, #1368
=> fix concurrent annotation map update

pkg/build/types/image_configuration.go, pkg/build/types/image_configuration_test.go
=> MergeInto should include Volumes

pkg/apk/apk/implementation.go
We are sometimes unable to expand an APK into our cache due to an opaque "context canceled" error. This change attempts to address that in two ways.
First, we drop our use of errgroup.WithContext when installing packages. If one package fails to install, we'll let the rest run to completion so that we make more forward progress towards populating the cache (if there is one). Even though the overall operation will still fail, in cases where that failure was transient, we avoid throwing away in-flight work towards the other packages.
Second, we'll try to extract a cause for the context cancellation and annotate the errgroup's error with it so that we know why the overall operation was canceled.
At least one of these changes should help determine what's going on.
=> Drop errgroup.WithContext and add withCause

pkg/apk/apk/implementation.go, pkg/apk/client/client.go
This should help us paper over some flakes we sometimes see with these requests.
=> use retryablehttp in DiscoverKeys and pkg/apk

pkg/build/lock.go, pkg/build/lock_test.go
Previously this would just return the intersection of archs with warnings for any issues (or an error for fatal issues), but that only partially locked the architectures because anything not in the intersection would fail.
Instead we'll return a map of arch to config. This is a breaking change but it's used in exactly one place and I'll fix that when I bump this.
=> Make LockImageConfiguration multi-arch aware

internal/cli/build.go
Missed this return in a refactor.
Fixes https://github.com/chainguard-dev/apko/issues/1448
=> Return err if locking fails

pkg/apk/client/client.go
Applying same solution as in https://github.com/wolfi-dev/wolfictl/pull/1393 for same problem.
=> fix(apk/client): silence request logging

pkg/build/lock.go
We were missing repositories and keys that came in as options.
=> Make LockImageConfiguration incorporate options

internal/cli/dot.go
I really need to pull in an actual version parsing thing now that it's exposed but let's keep this very simple for now.
=> dot: Do a slightly better job

pkg/tarfs/fs.go
=> Pass through ReadAt to tarfs

internal/cli/publish_test.go
We merged two PRs that both affected content, reconciling that.
=> Fix reproducibility test digest

internal/ldso-cache/ldsocache.go, internal/ldso-cache/ldsocache_test.go, pkg/build/build_implementation.go
A few nits I didn't want to block the PR on.
=> ldso-cache: Fix small nits

pkg/apk/apk/repo.go, pkg/apk/apk/repo_test.go, pkg/apk/apk/version.go, pkg/apk/apk/version_test.go
We who parse the constraints are curious about their version.
=> apk: expose ParsedConstraint version

pkg/build/lock.go, pkg/lock/lock.go, pkg/lock/lock_test.go
This ~regressed in https://github.com/chainguard-dev/apko/pull/1654
=> Respect arch flags when using lockfiles

go.mod, go.sum
Some other projects use new go-containerregistry, lets upgrade it here
too.
=> Upgrade go-containerregistry

CONTRIBUTING.md
Signed-off-by: dann frazier <dann.frazier@chainguard.dev>
=> CONTRIBUTING.md: website link for golangci-lint has moved
